apiVersion: v1
kind: Secret
metadata:
  name: chatto-secret
  namespace: chatto
stringData:
  CHATTO_WEBSERVER_COOKIE_SIGNING_SECRET: ENC[AES256_GCM,data:DUw3UQl6WJpCko7m+6qQYmVOvCYSYj3OvSLCtH/sQ1Z08zD4Q32WvZFjI7tH28cqN65VXHqr7Ydpzrq6yVdx9g==,iv:5Z4OqyffgCU1BY5G80Gu3Ssc5m1oU/D3QswWes6mqhw=,tag:+X726pXNCVEk4KcROzKQ/Q==,type:str]
  CHATTO_WEBSERVER_COOKIE_ENCRYPTION_SECRET: ENC[AES256_GCM,data:A0B4GEg6/MHSi39tiIZKo5aXeEGFZchyNaA8ptGQJh7nrWGtpKGhpY+8+MOnnFg6bOedkWkVAYRwIl+KBKjw7A==,iv:6NTnPNSelmpEaZqD9IEsjeHVkJF3LnpmXmLuNeXaqhA=,tag:41ZzaTaXRPZF6q6v7upH5w==,type:str]
  CHATTO_CORE_SECRET_KEY: ENC[AES256_GCM,data:Kbik3fCNgixSX0W3HikESybP6qgxOslBXSsOriXRc9uk3vnrABQTs0x6T4FHXYmVT+901hZribeTCnIAS87Svw==,iv:eXDtVLv44Jqqf4M1g6ah8CkK/BUVNI4TB3DySQvy1yM=,tag:nXZnwBx1ol6OTlY4tJenpw==,type:str]
  CHATTO_CORE_ASSETS_SIGNING_SECRET: ENC[AES256_GCM,data:YWdYwEDtsHjk6N42jxEUQiw0V2ZFJQKbhaavCrEvfWsX+rexWRe7vhBCbxUbM0NC36K+NlnjAwWpr3w4i4rk4g==,iv:Vfs4wuhiDe9F+/fb6nrzWMpebAaedC6q/By+W/Fj3OA=,tag:njEMPR35bPnnpPmUlN9xFg==,type:str]
  CHATTO_CORE_ASSETS_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5knC4GgKYVsfiOHSehrpt6KnPlW3Pziuj1k=,iv:+/Aq8BWA6xmR7Qe7G+iptQM2tdTfOrXuHY0n5pBWe/s=,tag:ir+y89Vj2jcBg1ABvFD79w==,type:str]
  CHATTO_CORE_ASSETS_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AdB7svtpnJp1QsRyuTouF48CkH7B83Do2miqQDZBDRqjVrXjJJSmweP8EAiQm26pVZYXLEdnT16S7LNwQQ2CoA==,iv:r9qowJ4itY8H/7NmKeiIHUZw7JEfs7lR0EpTu8FqmWM=,tag:46yd96nXAtsacMHkbccYug==,type:str]
  CHATTO_PUSH_VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:OB9HpPExjgOgbxnyPaFI1xzlfx3+E2hTvxO/Z7lLVrVFOY4qtdYZhEyvbklzfsBFQ3Gq77QgdGcluUGzBdFYeUXlkgoqEbV+6kdj/iVXXem/uMxEZAJM,iv:qNQpTuBUxnpbgq7hdx+C+tlTsERA6Xw005SSe2trDDY=,tag:hOLxDIxHxFls2KRq9x+aew==,type:str]
  CHATTO_PUSH_VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:Em8crBOIR3qkg/iRZCCW3UV1nbVa19bpAA718ab0Ab+5kQdqqBzTYUmaBA==,iv:I2MmwbtcKTW35ChQJpzyBd4zKj9QE2BLlxhLHmRiXnc=,tag:l1DSivlO5G9eqTZ+nECxjQ==,type:str]
  CHATTO_SMTP_USERNAME: ENC[AES256_GCM,data:+d4d7XnSLpUV4xokGHllmPGc6jq6,iv:5xceRrS1zRtDKQ0quR8+rGEaHExyaWEOq//tuWTmKWw=,tag:hmfs3LCPSodwFBFz+ivWlQ==,type:str]
  CHATTO_SMTP_PASSWORD: ENC[AES256_GCM,data:YLYKftIyJdSAKX2141ZxHg==,iv:slS5XRaDk32bOOnszV1T3mbedC92vDUcdxvf9M0eNZI=,tag:hvD+N93xW3Xqjoq6znTKbg==,type:str]
  CHATTO_AUTH_PROVIDERS_0_CLIENT_ID: ENC[AES256_GCM,data:LdraWws3iXKvqwrIRPKpePbzevk=,iv:T8x99It31syugNXigXZpbVpGgDtaQIPBENsNT2ArKEc=,tag:u+VAbfbkTWY+0W0LdHQnHg==,type:str]
  CHATTO_AUTH_PROVIDERS_0_CLIENT_SECRET: ENC[AES256_GCM,data:NBr/HfmJd5J1VV60I3uRcPMUWiJ2GHgikM0LCOOLJL22RspVu2nKHw==,iv:jNnZ23uJ5oJqz+xLoKcvps0pw+/Oj1oCWsPSGVnYOmo=,tag:YVgu/luR46LoRcLDZJ6ADA==,type:str]
  CHATTO_AUTH_PROVIDERS_1_CLIENT_ID: ENC[AES256_GCM,data:wFXmdw5jRoWbNJ2vaUbd0DgHwUTHWk1g8f5P5TQDDJRFLZtPbBHA1y960NqMXZyEfLrVWLY2J5CNQUzDNLwgvMIHl/+YPs8=,iv:u1KP6uF+Vw0q+VZ5lKBYbTXPJB4+DNWI3hJLngbqICo=,tag:vP/Wi168jO72FQW+1NvebQ==,type:str]
  CHATTO_AUTH_PROVIDERS_1_CLIENT_SECRET: ENC[AES256_GCM,data:nAVVHjHtnE7TvkG5F1NyIDY4mrq6KM/8DkP3C9eHOLZpsfw=,iv:mTyN01166TdHxHoxdJs0Ui1bXIFFAQt4fcymMVv13y8=,tag:wKwnymFBzFKZG/KNioniuw==,type:str]
  CHATTO_AUTH_PROVIDERS_2_CLIENT_ID: ENC[AES256_GCM,data:R7Dobxam9y5VH2qBlwYeBmxaUg==,iv:Mai8a6tuHOpcqDapKZs4JdJSRKpyrtMrtfG56+O3Dxk=,tag:ICgouYF3a37NC7vfn/SI1g==,type:str]
  CHATTO_AUTH_PROVIDERS_2_CLIENT_SECRET: ENC[AES256_GCM,data:+5EpOHu0BqQagO2n7yrN9/UpSKLAZwZQZRQLsnvDT9g=,iv:xE12hh2GpwtaBAdRlbtVOa+X4v1kRbdKG6YKSxcEcbI=,tag:KO8aANiC/+ludW6AOpqrSg==,type:str]
  CHATTO_AUTH_PROVIDERS_3_CLIENT_ID: ENC[AES256_GCM,data:7KAfGa6fZL4HU30PgjICmjtdrNN/svBKugBDkRx23t07nIFmW4Jv59B0Oqww4LzaeOD3biRXdSQia/LVsGXp/hiSg+Vc6ASz,iv:YNTyOlDeWzSCXbyVfFjtkuQF8nwsG+CcYb+0jOS+fDw=,tag:m3+1jf3mm0DcTPxeMKsf1g==,type:str]
  CHATTO_AUTH_PROVIDERS_3_CLIENT_SECRET: ENC[AES256_GCM,data:/yWXmO9bByoLSsDW+S2zRXrgkEUPS6bydL1zSsp4NyGbXhHr6JZ9tXF5+0t8tXl4KK8OivGC1jdgVf8ZAXld17wLCUhCBbdl,iv:92Te4FqIg9eRxeqeiSDCeQChW84nhVqYz3BwHo1obB8=,tag:SthnX863AryLIoFJygwFDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNmdnYWZWQVFUUHNjQU9z
        cmM4NkhTWlNPSjYyQkU5YzBiYkdwME0wUUVjCjVGSVhma21KdXoyNFpPOS91TW10
        dSt3dlVqeklnMTlqVWpHT3JaU0l3em8KLS0tIFgweUtCZ3BSblpzWllHNjVDVVg1
        Nm81N3JSU1FTS094QVpQRVhzcWxOdVUKSmWm2EbF8jOYy+lkKzFatwLsARfQgArn
        kL6sAlqUULQ+7YPJO9q7QGzZGOB0doZ+a5WmKjlyUX7zLtddV8TLGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T20:18:30Z"
  mac: ENC[AES256_GCM,data:+I/GBy9tX7/d/CGoGrUWlZOY8okm4osXeKvhpoQMbv14Z2QnYal/Sh5S98pQNgcD1vB/J1f5WKV4jHCnWk1dKW22yh+yIp2T5uaxzgnjdyPOgwLAgxPtK4Uk2jVwDKs6THGkIG9bbnPxtixJuCnhpIUygCQueqofxjuOWOilD04=,iv:cA2xWHBMNJqtQEcvUrMnlPsYTKJv1ei/q8BeiRZz2YY=,tag:1sVB5MK9mLexi2sE1iutcQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
