apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
stringData:
  #ENC[AES256_GCM,data:g6j1EiLtQ5XWuPRsKR7hiAluf3r6YfQXFDUJoG0rAebhCKB/4ALERw/0c7mfDTI34K8fZzYscj0rpG0vy256x+2g6agPVX4rZRXaxcYWuPaT01swehbSVds=,iv:uYWb3mQYF4xCQM+11PSsXdZtOSHpF39b8/TidAd0u94=,tag:Znwnc5Lo3DWB9oFalNlnsg==,type:comment]
  token: ENC[AES256_GCM,data:43/TsdeUmZ3ZVn94LEr5zV9XxeoxZJgBCs1j1kAJeNGe41xmFD1UjEHt2Q==,iv:8DcwakIRG7DDGmNKeY2yxd5dBelrzmiRDRWjrar8FpE=,tag:Jy8E0M28M9TF21UEqSGTLA==,type:str]
  #ENC[AES256_GCM,data:tyo5NPitEl6SbLMlqmROJ32rEzr2YLPEwJMtXm5TZqWRtZuJ7BIUZnYof1gNHraPixC7t0NXaJDhSBLjZw1f5x4Tk5dEVbxRfd0QIjOU,iv:RXBRAEwoP9/zwrHIdQOCOyC5rZbzVhWAJ+8MUTnWL6E=,tag:T9vmdXVmAarwq6bL3HfRsg==,type:comment]
  uuid: ENC[AES256_GCM,data:s28gUUCslHvnZlbsC7Lr2c2jUMtIy5oh8hcd0kkmoHK6Kydr,iv:rD1+6NFtAsjVLfbfsG0PX8MyB7CtYD8XMA0KcQEFHP4=,tag:dx+9BPJsa5xItx0iTe7Ilg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdHVNaXZRUy9pSlQwR3Nk
        NGd4YlY2WlZVbWU5VUVtN2Vndys4dThzMTFNClJMMUFmZDVxY2JvWHNNTmMvZk9s
        dmtHTWprbkhIcUY2YTJHTGY2cU1BbFkKLS0tIEZSL3FFVm9OVFhCS0s4TDJsK0RK
        Nzl2cDlrSGIzcFVVT3BCNjRGbEFrcXcK02stD+Lebm0aI6+HbNnkew4aVBbVQTxP
        cKpN8JUhuq8C6VxdBUDat9vgw57hWC6anz4LkkYCmsfQTJufrHdE8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-13T18:54:19Z"
  mac: ENC[AES256_GCM,data:NEX25HG1n9RBg2Sa4Ddb+70G8qjm7ukknIo+JdqPnY6AL+uDPKMqS8oaULSyBcxPo69wg7n8gJJsmI62R3beOq2Yx63ozxH/kkC7tnvYUlCjNq8ltSi9UB4wKQpD5j6nr6+t8DxJN/fk3WI8cRKJ1odsH2dg/GQ2g3K1TTJflGI=,iv:3bIoT7fhBvweMwYGFAwnZT3+JsOmL1spLInNUCTMCXU=,tag:rjq6VxzjCX9GYdmw9N73IA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
