apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
stringData:
  #ENC[AES256_GCM,data:g6j1EiLtQ5XWuPRsKR7hiAluf3r6YfQXFDUJoG0rAebhCKB/4ALERw/0c7mfDTI34K8fZzYscj0rpG0vy256x+2g6agPVX4rZRXaxcYWuPaT01swehbSVds=,iv:uYWb3mQYF4xCQM+11PSsXdZtOSHpF39b8/TidAd0u94=,tag:Znwnc5Lo3DWB9oFalNlnsg==,type:comment]
  token: ENC[AES256_GCM,data:8kgNfwGbf7neiASwrfBkg1oe6gsiH91lcJZvA6qxBhfjmgyAUbXWjg==,iv:AU30WvqKCrdo6oeEmwbyTnYuWwJAyAMNhN2pYZENAnI=,tag:ux3w6R9K/D6TOx5CpMqwgA==,type:str]
  #ENC[AES256_GCM,data:tyo5NPitEl6SbLMlqmROJ32rEzr2YLPEwJMtXm5TZqWRtZuJ7BIUZnYof1gNHraPixC7t0NXaJDhSBLjZw1f5x4Tk5dEVbxRfd0QIjOU,iv:RXBRAEwoP9/zwrHIdQOCOyC5rZbzVhWAJ+8MUTnWL6E=,tag:T9vmdXVmAarwq6bL3HfRsg==,type:comment]
  uuid: ENC[AES256_GCM,data:eHVuZOhLkM+nep33n6hE2RKNPCQ5oXmMFqpwQ41RlpwUIiVd,iv:Wh7R8wn0X8UpcUt1syiYibAqkIPX0ZyHGtgcASBtRcg=,tag:VafvOtPd47ddCVmlAWkVcA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdHVNaXZRUy9pSlQwR3Nk
        NGd4YlY2WlZVbWU5VUVtN2Vndys4dThzMTFNClJMMUFmZDVxY2JvWHNNTmMvZk9s
        dmtHTWprbkhIcUY2YTJHTGY2cU1BbFkKLS0tIEZSL3FFVm9OVFhCS0s4TDJsK0RK
        Nzl2cDlrSGIzcFVVT3BCNjRGbEFrcXcK02stD+Lebm0aI6+HbNnkew4aVBbVQTxP
        cKpN8JUhuq8C6VxdBUDat9vgw57hWC6anz4LkkYCmsfQTJufrHdE8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-13T18:59:00Z"
  mac: ENC[AES256_GCM,data:w9sdXnv1vCHhvAJr21/7N/G2VKKP75H+OPsy9UpgB7oBRfJ9EMJoWetmbg0bu71vlgWMerBlVsDN52O7M6JXsE89oaHn1sHfT8dJNwcD2ewEWdxrQspM4qrFLWNM/CRR+LbOoTXzwk4lIGt5pMtyITKdua88k7tILziKtSnteI8=,iv:AmJlRbWK1CV9OLwvVaVsmt7iPx6ujnpiXZAeuoT0Awo=,tag:9uS48YMb+piiqsBnp1fejA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
