apiVersion: v1
kind: Secret
metadata:
  name: pcab-secret
  namespace: pcab
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:IgveIf8Vq15L/xvXRt6URMp/oXKAUe5dq32o+0xRsIY2cK/scAunFJp59jj3lU7G8w==,iv:meyXVJn3yDQ5HlCaWB9SBVCgc60umn1dv6lPkLfmbL0=,tag:dykqYMFiC4DX4qbPoNg6zw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:R5W/7Q==,iv:0n7FURhuyLL8HSnCns36ktuwKsTUTCOaP46dXA7f0Fw=,tag:q0Vg0FXsNLCFLYdwkv1psQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:hWsyyw==,iv:a1F3siCMX4ic2WVKYoXLV7K0XDw48FD75SVFsc76Aek=,tag:u+EEAk5j8rDOk/1iOeOWOQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:rv+W91WBNc820O/R7fACPPJ2ErcTrSAQPQhwog==,iv:vfJ8Qgu/Z5MjOvLnA9oPsyNRolgFyO5PWF7mKrM5uCU=,tag:BDSoZ7krwBttw5r+3m8Xpw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iOsOCt8g23hVu7cujyXOfb3zrvxZQs0m3/Q=,iv:Gt+ZphZx4Zicplz8y9r57E6Y9thlzT2zrv2TJrCKpx8=,tag:u2FFoakWGdzJEBSU1rxXGA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:cNj5GvotZJohz9fRkpOcGlW+8DBg/F3z8l58N6091MlTD1Q67WXxAgwZO1YC8omxRDxxOnaoGX3/r0kapWWsbsoTFdzoRQ1KsliPsMrqLPrI7HAYfNLVCxcKkd9KJ0z77qwR9L15swk=,iv:N/JFnAbD0pw6hKGt8zd56n8TTpehvoXOixvZqo/0BI0=,tag:DwcDbhPSHzlKj60JNmTS2Q==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:WruaWDQN5ipN/dVT6JaalEhPAlOWkg1p5lStEG8VBMtRsb6lT958R0weS9Wgei0dWhr26Z/5ZmVbUO75s2jylA==,iv:kNEVnH/5Yi9eG5+CuI8cRrnGnlAjl9zmvRKUmdI2BP8=,tag:BMIm66rJtVC+OV73ETIatw==,type:str]
  OPENROUTER_TRANSCRIPTION_API_KEY: ENC[AES256_GCM,data:YuSwfKQFN9a3Mtpb4BNTBITt+Xs1vxtq5B/HZ7WQaCbBaE96jocxM0c/m82i3kI2KNbV0mfjXHYzJzLxwOaV9hvuBkjSyUZmFw==,iv:hoSJrd/yLSUjq42Nx6htZBlRVhcKfl0K4F6pT1uKpnc=,tag:0wrzAY1Di191x2qN0IVlDw==,type:str]
  OPENROUTER_CLASSIFICATION_API_KEY: ENC[AES256_GCM,data:g2F+Uox3J0LPK3qORRB39EM1g2V3PobQoTX0Jbf1FTNAOronVy2QfYbydQYDrl2flC+put3dg1eYlYsG2f0B/wRrppQGQNqevw==,iv:qkyPDI7oFRcI9m7uY7CJA1dERXB9onWNW7jYmqB+QQU=,tag:pLLoDI8difqKahggyR8LZA==,type:str]
  PODCAST_INDEX_API_KEY: ENC[AES256_GCM,data:SdFjP2E1Ho+qRsFWwMS4w+n/m74=,iv:nxwDZCr0lTV8FwltyzN9a1F5BPuZG9OEctljcz0fE3E=,tag:woMN3DpCIclQ+p4t2Vltqw==,type:str]
  PODCAST_INDEX_API_SECRET: ENC[AES256_GCM,data:zQNHXNG4bkasyoMsGFZxZbZcokvDkg9jRuCCudxD06v+UcAJgMGOAA==,iv:JuGLlj4eUjdGpKeRW3Me60TUbCc+f/YfGEy7yH+kqoA=,tag:uW+UhyHT7tZX448KpwfOSg==,type:str]
  OIDC_ISSUER: ENC[AES256_GCM,data:/MdCKjAW+nIL2jkrJHiAMbDWJOMNtmjSkSGaj90=,iv:MAg05VXA7vF6qz7hTR01HQGK1CZTPV6WA31fJMgdIgo=,tag:mvujkWd9zKTyvmxii5jPcQ==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:KtXiyHxR0SgRMTaI/qhpC9Vixy7LvzVxBxF7lgzxArEoFv1gUCU2K4AZvenWivsGmzEMLMkIhiLV32L1ERF+u7AM0seTZhL3,iv:lvE0NrTioK07TwwoopRAH5vozzPjFhjt+rbkm6VSTzk=,tag:ZwbPQDWJoen36YeBVZuy4Q==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:KAnUaTpGdqSFHDseQJ67W1djG3/dJWPMBzUGCXvcZSNzaDTo5D4BhKA2Ilp6NeNmKbMIe/cNzKJQW4pndjhUuiK3ExisEWjw,iv:C229S9p+wttbEhev5hLx7iEoJm7vmyb9vRO6a6JCDvA=,tag:+RKZaV9sS48j9thMG9JHIA==,type:str]
  OIDC_REDIRECT_URI: ENC[AES256_GCM,data:1t3OscQEb7Sjest+46GDyGswhDp+j+rhXAawpQVoMSa5DRw6hMWn+fF4dh0/YTQ=,iv:yZrh3oILDYnHrkoqmwjjK34YiINBAC4y1UcM42pfK9Y=,tag:LYaCMxhay67bk3N6dsDPEQ==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:KIKzXoAEv+26cIuc+ajdgWSRqE0=,iv:TRpEh4V2qnVmouoQqK4JWUmZUmYDjHeBd7n4j2K2pAo=,tag:TqA+chCR0F3T4k15Lnd3hw==,type:str]
  OIDC_PKCE: ENC[AES256_GCM,data:HMsUWA==,iv:YEby0v4CYJ7R9DtEII1Rb1bc3xZ2z/IWpaYTjjHFWSs=,tag:iVp6QI7ff49pAqGkGyX1Gg==,type:str]
  OIDC_AUTH_METHOD: ENC[AES256_GCM,data:R2JqHjaelwZvd07PUMmMQBIqXQ==,iv:mlys30YRwiaUJ/OBHatkez9b/I0VzwpegUdqMHD4Thw=,tag:g3uUJT2DkzblItHDq714mQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eVhPdVU3TnZjQmZ2SnI0
        TjJUaE9KblR2K05EMWo3WW15dWxXdlh4QldVCitPZWJ3d0l3RWk3V3JnMTRGRmtt
        ZXhKREtBNjROY1lmQ1BNbWlEdWRMdDQKLS0tIFowNXRhRzBTeHoxK2Q0NFdEUG9n
        UmpiVS9EM3lkWUUxQ1IvWXpSdHd4SGcK+wMIkNgmNuRL3ocFhTN2J3ky0SLsYTp1
        1dfdUn5trZQsJcizu3bAR15Af1wvncF4quQv04DtYF6SG3xmmk6KCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T01:36:28Z"
  mac: ENC[AES256_GCM,data:3LOD8qqWvkM1CJVNbF3qpug2Np4vdQ0gV0CtZZ32lWcW9bfwFdTIyOEsBzy/aftDyJ4+8oyPfw5NBvbsXAFw2RcnkQTHNPi9lbblSlW2i9C++rl2pLM925EmqM1z5nTvBvr+8OuwcqJ701Y7SlyEf//d/HvC8gg99arG+PFUzsE=,iv:pJWlcB+wUpQn2MhpEgKe9gSdcA/3Xvz9kENngn69yyU=,tag:tWuLR1bNupaH7ROtiZZSzw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
