apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-zac-pizza-configmap
data:
  config.yaml: ENC[AES256_GCM,data:O60V1VC5KvVKO8VxOGp7Bc0IyVMRV316FCDSYGK+oOSqyC4couOlynM7XfVEWnz4dm9zl0idYfkCrcJRVv11flFpLKQXmArDPQ1MbMVLPZJ0q3+7in1BRQwb1VV2rNk7TWbpwmdXNAD/8/4zqO4qNPZyExiVNKi365OFZ8pv++JGF+obYDU0WIip/ZQQNXEGxWi46LSrk/HFxqNaHtro1HVKoMXqn04m/MA+m1f57zaTj9W+tsfwW5jEgbi00DSpVG120UoR0ItW9CwiZee0vyUj0nIXgAXbXyJOKHNEaP40sHmMzXV5SD3y8uTfdwYDIgt/qHmRT7r/InrsDCaiR/L2hziTZfwhdJ+HWXgnffr3UU32xKnerSZLenQ7JmzbX4sgyrliPE1p,iv:PEZPJKEZZDiMsNuWwwNYY0c64sOSSvdrFFsfu6Zieps=,tag:Xpe3M1e1EgZwtVRXW+Lkaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ2lyUEptWnlUSzFCanUw
        SFVZRGkzSFE3bFF0U3dheDdML0NzbnN6Q1RRCjRmZ3Qvb0pPVGV5V1phaDZWeHBM
        NExyanordTNSQTJsWEZSRlZndytJdDgKLS0tIE03UEdjV3ZhbW9RMm91OTlZRVc4
        ZWNUSHgrTS92cVJMUHdVYThnajU5eHMKnliI6KeWhjMNpbpJbHP83od0p/HMTZuX
        dXvU1y0sOcwWRYTEazf60bIrpvykQ4SS6XvQdoHgs+Jsljd5/OC4Tw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T15:37:25Z"
  mac: ENC[AES256_GCM,data:dKqXzJdFFbzQBG0BZaLKjZgXHoUGDSkFjaWhXgv3rO7saJTcRFZ8SEW55Ddx+u1Z3Tk/fbmdMIN18vX2awyKwr3omDxptTa0ZdNm0YIRw2XkPS0wLYDPjU0UU8KxwLG4quc4gC5JvMzwhv3XXpAOW4ik35iYoj/rzpyMsTyBsVg=,iv:FpnVq4zCoyLwDx+hliu/WvYh32k/akc5ZFeAZiaiVS0=,tag:uerXWmPxhME4XqXDrv59Ew==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
