---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# These live with the Gateways because a Gateway can only reference TLS Secrets
# in its own namespace (network).
resources:
  - ./production.yaml
  - ./production-heremag-free.yaml
  - ./production-zac-pizza.yaml
