apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heremag-free-production
spec:
  secretName: heremag-free-production-tls
  issuerRef:
    name: letsencrypt-production-heremag-free
    kind: ClusterIssuer
  commonName: heremag.free
  dnsNames:
    - heremag.free
    - '*.heremag.free'
