apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zac-pizza-staging
spec:
  secretName: zac-pizza-staging-tls
  issuerRef:
    name: letsencrypt-staging-zac-pizza
    kind: ClusterIssuer
  commonName: zac.pizza
  dnsNames:
    - zac.pizza
    - '*.zac.pizza'
