apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heremag-free-staging
spec:
  secretName: heremag-free-staging-tls
  issuerRef:
    name: letsencrypt-staging-heremag-free
    kind: ClusterIssuer
  commonName: heremag.free
  dnsNames:
    - heremag.free
    - '*.heremag.free'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: heremag
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: heremag
