apiVersion: v1
kind: Secret
metadata:
  name: buzz-secret
  namespace: buzz
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:CnrPsA==,iv:9K4nx/gFB2wfc1B+Q64fHxWB2I0qppy5GJD6UDnQ4HI=,tag:YPQj7Kkv1YkY6xdW5x8LRA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:b3qkMBIHk2wFrcP7I3iD7yErEZSXa0gT6/2cevN2UxeEjXGGF720zYT30RufGnk+Mw==,iv:Y7sr9Pn5xf0x9CN69B4J65i/U+jbuTyvYfOYM+9CogQ=,tag:UMnMi8Dt4QQN34NgYQvJBA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:G/eZbA==,iv:DqteWj2wypa83byKfwx5gxN87SCMa6gh71DO3TB20N8=,tag:mKvrm4hmGU+teP4G/A1wkQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:mjO2bniCTwM3BJxn8FrhKHSDfukXlU0p5FbQMWr0TdM=,iv:Os8vOnGso/SqvzyrQPcUTuHZZrUoZag+wXhah7gJwx0=,tag:kbHlAvb3D4KIMhC20jWR/w==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:WJqInlk5vUQy3d5SgfBzYy7Hj38EwjypRv8=,iv:TdXH4yipphlDjsrqsWKVQ5BPbfq2V25H2c4oPiDPvJc=,tag:ROspCKlxdx43drrttj1qYQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:G1cX3+0or6OyMcwaa1o/9jt/4bB+7AAAjhKsU8W7tXG0HLUPEuxjjSDieB2C/aR1XI26yO/8RP1wV5riVTj86hDFDegMOFAEgXddazKJ9pN93shhgnQ/ywbkYt17DNBAm3Mux8mbgdR9vtIK,iv:r9GlDSEWCBSDS0SJa2qQkDGdghaifeBMrnVNG3NNBpU=,tag:CjU5tik4sLpevuywL5Qwiw==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:ShZXXIskyxbnSN1EOx6rCFrqPMzCsuXnAY9t/D/pWQimnXvpuIRvpYevksRxU2vBZN0ZGq1VDbbYLTEtSKTZflk7US2kmdE=,iv:7yG+vIMqNeG21E5qzvs5JgUX2ImjXj2mbbHi8ymPv0w=,tag:Sku7tebTEXtMXL7GIxr36g==,type:str]
  BUZZ_RELAY_PRIVATE_KEY: ENC[AES256_GCM,data:cMRV3e/hLCt0CO+ev9g6//xY8I7hxcqSNrPQ6liiAwcLJNJobEEzoiRwKaZD8JXLMC80CFw2eCkRHmVLxypyaQ==,iv:+7hqo05V4oLjnP+j7Vqk2Fde6Qu8MhDKIT0h/n0WdzA=,tag:keFsMZ9i4wKwPH0xjZjJ8A==,type:str]
  BUZZ_GIT_HOOK_HMAC_SECRET: ENC[AES256_GCM,data:kViMRLf+IzYUL3w4ys4b5NiJqSmaO/LdTwHcNwM7+LAqPEEMhSGjnRG14A==,iv:cuoJKDI+oLg28P0x+wtpz41fevrggzX8P12gGeH9JzA=,tag:uLEC7MMqqugKyknOtQuJMQ==,type:str]
  BUZZ_S3_ACCESS_KEY: ENC[AES256_GCM,data:CMLKy8omeVdJq3S1/OkAdyvJZ2pbXPEmq8E=,iv:N+FwKlLIx5pLGY4FnYheqn0q6MQ91SsrSUxAwC02R7s=,tag:xmlSFRg/hpNw94unP5bZ1g==,type:str]
  BUZZ_S3_SECRET_KEY: ENC[AES256_GCM,data:roXXRIkRAEMbqd77tU/zFTvLTaJ1VLrhlXsxtYL2M7ykbNmWyGnEjZDQg26R7REx4mx4XejhyvgXqGkrr+/Y5w==,iv:vMl8NbBckDhYIVN32CCTx2SXEwADfZSTBZJmdF0vsFA=,tag:28zBLpG1TrSqVN/F9zRqXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa0JmVXFadE12VlNjeVZE
        V1dnb3BiemhGa2VNV0tYUldpdnJ5aEkwcHhZCnY4eWxCUXRqd3d2cDcyZG9hU3Z1
        Zy8vSWI0ZG84RW9Oakx0T0lXbVI0UDgKLS0tIFVtMVhTSmdrQTU0dUExTTUzWGww
        OG5hYmVXMHB5aWhWaWo5VnlUeFF1TGMKQV3/EEByLLcYA35wal7QK4cTeIdyAv28
        ivyKzBWo4nmlLBQpveIG/Ijs0BZibDiiycZlObC7hvQhXN5+h8vaBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-25T17:56:04Z"
  mac: ENC[AES256_GCM,data:EUzlOOFb0Aar8UiEQ473Z+NUUAki4++7xjxTq0zzL1uHn1BS1mUBLohYWpiFWtRy4vd7L5+yiTHDbNh/myc5MKbmAHWiMXVK88j7jgI3q4VDjFTb7xiMBzryjwgsCLwbXWXip+onPKmFZPLHMI1FMkteTsagDycA3PPO1d53ybU=,iv:yQH1t5P7+WZ6Jso1i668+ZzmyCmIcRAtE0iMJ4n9ALA=,tag:d8Q55/q2+oB0tf1G4Mh+Lw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
