apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: democratic-csi-driver-fast-config
  namespace: storage
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:VQt+KLOZNRla+PEbJjJMy7m/zCQyPoKjudt2Law+hCe9p8h+AXByNnWXVQRguVVFnlHj0o1s0n1FT5wBlO4XPMLbmxuSLxcHIyCsmd2PoQVU6IcLoAGWlxzYOj+jf7Q8BMJf4IbVa4L1Xo3qqoirztLMdqeaXammMUzviNRTqPJMiYv1ALXx/AKuMYha51sEiuU7IePTm022oMJUaLxTtduTC/tjvJSc+6H3AZZif2wiaVlWvZ4UJjDSLR4aV4/eciQIXkB1i7Yn78mWWTwSkv8trM/hwToLXqaqp0UlF+TiAbjJnJJV+zyWfQdtBWWZ450sKn1RSu+m1LvprcoyVjnpjSa8pQF9+BEX02indnwKIo7yyqM8S6ss8il+cw8XKGqrnOxFSwJEtkk/BPMjw6eACAY+uA8Acck27TxhEMXCubnqMxjge6cWO1w+ASUjTUxMpBwH7LiEmit847VbmNWumflAsNgtbMoRZbP1TUmx+2qKG/9xVStfsthKQSXzsRyCcT9YbI96xnG5fQrAwHyeJ6au254dB3Ogqih3m3SiS0IZN6/EoPMxDkVFtdjl1mYCYUUTYeEzS0Xfslf7MLyFmgdgShmNieBElZ3KBHY2S1o6bWFQ5nKOrDTKKa0A3og5M3g9WrCoM5sqDUneXBKgzv2P26Q12QfRIYZbr6be5yKcVAMaWO6ZijjroxadXnWy34WLInv+dPzjiVfRXpLpWT4Sz3ejX9mw39ZwjJ7B2dRwYz33ptqQuwrMimXvRg8HO5eednXAyB4UZj45IuHT8fte2ZS3JS4ue2MhSA9yrMQEa0GeDtLcJGQrfFaagfCdhMfuGsMeOixPNwY4zmdCu4t1Y70N,iv:yMO48pyrWMH8hMO0gt0u99V31J8yD2QvdJ0knoWW6S0=,tag:ggujVF3D1gn9iPfNICil5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMkdGeGJVbXBqRWlLMVNk
        RUluaEpmaWMxcHhxQ1ZaSHJpM0RvZ0h2ZTNJCjlmdUJzZHhnaGlrOUQvVTN2NmQx
        c1JyR2FNTk5UU3JMWTdVZU1nMi8xZVUKLS0tIHk4aFJyd2RpL1BTeVhIN1Q0bmY2
        Wkg0WXBMaHdsRHM0dTJhSGIxYVA0d0EKOBv1ibcb6krcQ5+os1mjFifyhoFMLh1Z
        jskshby5ugqAGfzsGnBzPXR23KseFS3nbu7yyQEmBvvsqUp7s5jU9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T20:21:31Z"
  mac: ENC[AES256_GCM,data:yIh4cRk59r6hZEXUN06Z+miSUYFLVA23FG6bfeBz4wCdnxEWuY+qd/RcNzr9oXiQqJ5s6cKuLv/e1omw48L8gxBFfO60QdJ9of3utTVAPNH2fPPnUybtix8VlxFbbjGswSWsa2ZLynfforDBnTCWLRFudKgRRzT7DJ9tcMQl3Co=,iv:AluYtSg0DbVxhxltHPflDw6bHwlSfFGjYheevfemWr8=,tag:o8Tgvs+sjMjx0A9pJotdrg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
