apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: democratic-csi-driver-config
  namespace: storage
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:Dtk8gIgVFKPcnDP9opiDLaA3ZzFlh+OSkD1nKRrpS4wdUY++Xxft7ULULQPPwnKtduDPhZqY5OXClBtd/EgL5lPA13FDCZJY/kSZ+TeCxM+vbzzc7yIClO/O0+45/qFqsTmFdx+t+V5iWaLaqrkIqQcQ5rGpz8UNHeAy3LO0Hg8FgTdATpfZk3T9t0PtQ0o0D0Cta/bHjIIQJqUdpcrVMyPhx0zDicVnELsBZmu+2WKCthDgZBUjjE5sdBldSY+szPiIti3x+LRRKlhFBr9ni88U07I5Qi31R7ueUAtRFJfP7f3fmng0KrPNkZcC2Brs0kGtjkin9fNXY6EAUMnVr8Ct24/+lstH3HDbcfxrltQaWW5INkuO/0YB/b0dt7t/MsdBNetTHSxKVPY2/LO1TvhC+R7/HRlUCjjBci7oziQwRtQFLsc7rqnizVBqElFeoKns97XgTQUAz/ZmyL6OQ+2a6C3zADrj1BjBE0+e2wA/y7gtu+L1DHMJpSqngIZC6QTPWaEglASAm3CDoSxd4pzH6LwbbVcxrQqqsiylgufN+G+n9GUK1PeoRzRw5dSEvQuBahf2rIMnNp3u93pFcdH43YUvpTVtQYxQC26Qsw9dGGVXXzuX1WcyhL/DWQZaUyjDCga/iLa89UZRXdBR/kQwSCKBAk3P75fmocdd01m49iEHuzLxVWBm/1kC1NDa7rH5c7pBTTBeGdmX3itsTJ2cP/cW/xE74dbbEsLxW0o+RiqkIgL0k6SyHnPVNAC+m6+yJm70egfeecdCWsXWW0hldLr951gc1JOcXMt5V5PHJ9mltd4ly3Xy7TuvovK2eoSiK2oV0IjA53U5cWU=,iv:qaKyYbxM5LMGbZKY8OeHad5PtScc1pfKSfaLTIdGCm8=,tag:iB1ZTuSM3AxgcfgSe06EWQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SGVSL3FPeXRkeW1ESURw
        TU5nbC9jTDdCSFhvNzJEb3JGK2dGNjB4Vm1nCm4xUTRBdytTZzZCVEdxZXJ0NXNy
        cldsOURHdG9YOWp3cFU1ZEJzdHVLNTAKLS0tIDRKOXkyUXlpb1oxVHZWWDkrVWZa
        cmZmYXM1U3dqZ1FOa28ydjNlaGcyemMKEvZ1R1VwwcaUYqHPXUM/lyqnPiCGJdhs
        UeindLVU85CptDHamIgCiYRo93/T3S0BAC3gxig9Sz0oKjLMjBYIJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T20:21:30Z"
  mac: ENC[AES256_GCM,data:LQlmtwRcGRHzk9ZCcDLnpo2mRBZ5nqDuA18gPw91ZNhRgWREB2zTCYVqjLBAH6k0mIjE8IE7QJJlhWhu4Ih+jPJP2oPDH8OMSVOke2SPoTpJzkQGCWShgalqaWBrNg8NO2HJz8X/9W7ChBW99p5oycsqHmyC+wKjanruQy5J8zA=,iv:IDua5zqLL1lmAmlWtHU+bh4CcUUsfanrX80lJ/GmxFk=,tag:Eujrv726gApFs1RLis2sRw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
