controllers:
  lastglance:
    containers:
      app:
        image:
          repository: ghcr.io/krelltunez/lastglance
          tag: 2.0.1@sha256:1865171d0c22ef8dec6c56f56063641bdc7ad19753b69dd748a0332033be89f3
        env:
          TZ: America/New_York
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi

service:
  app:
    controller: lastglance
    ports:
      http:
        port: 80

ingress:
  app:
    enabled: true
    className: internal
    hosts:
      - host: last.laboratory.casa
        paths:
          - path: /
            service:
              identifier: app
              port: http
