apiVersion: v1
kind: Secret
metadata:
  name: trek-secret
  namespace: trek
stringData:
  #ENC[AES256_GCM,data:hQ8VuuI8WnNOaKC3zXeVtbz9vXkj6M57kadE+0GxlOtzzKOajGZfh0etehuh0ZvMQs1GOb/ewyw8bgQo3E2W2fIsvxyVLTc6oRF0,iv:wVp4StYqW+ANy91VPXUboMsSsCO2UD8vhqGZntMKuSE=,tag:IxJkSGiW4cRjBVEzTdBzHQ==,type:comment]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:G2IOyHTtoERtXB172HZhykau4E85yMK9RMMK/kCMAQA1czrP46jewpWCfmtIkl2LTGaeJdu00cL4R5oUoL8GQg==,iv:+fLYd1/2HpqHNjJhfmxls1K3Nbw64wMr1fhZoCLX20g=,tag:xxzO1kR4DOWBXn2Kfl8I8Q==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:TMtnNCppClahQIVyaZbojse0tg==,iv:jcaDIZMCiRbRur9TKQEVrt/9q76wpi0J0BIxaPKpFXU=,tag:u41s23X/HACHBWiD95XgrA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:EOW8F4k77xaUc/HY1czdp8pyPjL8Th1yAOtK7Q0g7Gzv0Q==,iv:n92dzWkRD3s3I5AfIK1LkSBxtEleUtxRaBRyDIQqZfs=,tag:/N7fAEwRgGt53Vkn07XB9w==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:qyzM/NP3SIHvFAx8HOqZHlofsXjynQfcISJTiKMObvD5q3/UovjrTEUMl6GEF5SKQgKYJfONlKkJqO9XsF8r5ZJxZbJeE+F3,iv:QXD3uoJDikdg/r0EBcpWxcDB7UCWcpk4WZoOCJKrIQk=,tag:6NNB15qNB0oH6eu2Yd6/Pw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:09RohLp1+le9k6naypgJWcjIbq/zntSLLs7c5e4GChVzm9yOmp1LQCXGEaPLj5KDO4vLvzWfrgSYRBG3cXul/Ky1kK39SM3P,iv:A1DNUpFMbxzE3fQ9XHB92O91Xb3sk9VN1Hjmg8DMRA4=,tag:S920Zh2gK8wd8yJkGLiK8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESmQyT0xpVTVrdExHS1JS
        NVVzeHo5VTd1L0NQbWgyRTZTdDFVOTl0MDIwCkZHQUU0SjhUT01JTlVnRENjNTdM
        N2JTdDdRWEwvdk1MdThCT2h4RHVYcVUKLS0tIEJSVXBITEk4eFBsWHNjV0lsRjh0
        RFp0ZUIzYWVCL2VjdUxjTjRxS2FGVHcKww5+EVkux/dYlZrY+6nTpdPEiuK/02KT
        DTpQy4RAffzZWEZnG1qjjY4A0xfSLy+NxQBcEwaWrWf0kGzS/a6ccw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T19:33:55Z"
  mac: ENC[AES256_GCM,data:rMILGtVmAj3jDKeyBz4cxoi6N2Z5UpRhX6KgHlorB6JRCa1jyWgCPfBRjK7b31vfjAOQIg8NPYAw/kniBd5oCkXXJuJg+KgUjlQJ/VBphAx1QOmOXLMdg15p6OTSvDeZgwy5LjyFyON+I3xwZXflVneCUU8Da7k7l3NWLubUKic=,iv:dO4iCObsDjWjOJodGhLF6FthWPrDBpu7bQv3ny08e6U=,tag:eV/NGw0A6qZRGowb1gzz7Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
