apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
  namespace: forgejo
stringData:
  #ENC[AES256_GCM,data:F+iedWxseHK6ILcgTfToYsy/swUZwTkl8mloWjJEo7y0bJ6leTXhu1cQfrFsZJgQMFTstvAoeBU9faQbP7zNcis1OdGIIVy3vMM1XShx,iv:WYYaXKcSiyLcF0ijOgezQdC97UF7kuyoPdMbsqN7fZg=,tag:n06j7YSew/+wHQ7flLf0Jg==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SuZYn99+fA==,iv:dRhIfZtb51DvvkZM6sKiYGMVLi8RGh4iXTKYnAlv6W8=,tag:WzZFRk4q5OSDy1DPhZemRw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:txrnAll5cg5NNDFXAl2QgogpgUt+i4SqnXWPvUm+w8/K29w6aar5pgO9Ln6P6FhTsg==,iv:Y8kfC4+qx78CL82/zgX6QyqTVEIUqHlfNl8pJ5rDJ50=,tag:0p1BVcf62LyjP/yxtc++og==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:DrErTiZOLA==,iv:OjPc1M8tDf/HOeBZmWX9HOXZY1gKHLeGooh0lm44KMw=,tag:MmApxFBfXQpc28M0ITFXJA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qxYWMoXbsP6xwwDg0H12j7b+/XKIH/gDTA==,iv:H0nm25AX0MVWR/6+37avc1r3WHa1M8XkQoRCR9yGsto=,tag:hV7AI+g97aNgmllPff/jXQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/KK1Q4cWn4EzkuUeO1qIPSkLS+p7Yhm2ht4=,iv:A5E/Wq56Tl2vqzehaCBnLKrM07nStDRscL1niEicLak=,tag:UcrzMfFzyPlSiZ5tOt6NkQ==,type:str]
  #ENC[AES256_GCM,data:Ynmui51sUl6xjP5ygikw32L+bnRcYrpKdxTq2jiV87J9MpYs665xBXyhjvJGXXTXXucM99v3LQ==,iv:99aJ2xVhwM9UxlsVhCidDMM84IZUurusXXYQgLDJ+Lc=,tag:CyuRAlHW8lZDFZFdrgjm8A==,type:comment]
  FORGEJO__database__PASSWD: ENC[AES256_GCM,data:L9WwniuvSD57zglgnYs2GbME28QgiI7Tpg==,iv:I/Z6ct8t4neyGun086M2k/pe2p2dwNUIRGbRzPGa4V8=,tag:yaBN9/WQrt/6URCIrPUi3Q==,type:str]
  #ENC[AES256_GCM,data:5KLR1dggk32uMUvgD1ZAO5PFbpFKsKE9HF/YMvSGSKAfOhMTL2ZAVeV3Hbj0XoopTf9txi5mcqBKoBPE/BPjQ8ZhOkgwD7Nk2lauig==,iv:AhtUL6lvEyxm9whpKFxONO4MihAEzIZfXfM2XTbLMlc=,tag:Nf0880T7+OPv+3oF/Tf1fQ==,type:comment]
  FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:qnINE/VeOvcF01ESH/QzrLajniSugDT15q9rzmj3ELTCAdf+YJ4Zs+Wb2w==,iv:5doCSBFEUbQhnZgvZgU4N6PrEMC5+lOJVmPeW5kPfNo=,tag:MM6MUP3sZMN6Dj1kS23wiw==,type:str]
  FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:0WjzFms0ZE+xiorn8LGhmgbYj/ld2a5+rFPkdqNuafZsasDJXievMGN2Mkgm+bfoDz6F4HzbnBgIHTczll/7hzDeKXC/mn/srGLjaE4aFM6ZgxGgvF7DjKuZtJsjD9sjAiPWLG0v0agF,iv:htU9hMAtdV0x885Fnk8SIxTMG/BrxI38bXcBWl9wVgU=,tag:fWXfW8TYr9+ZP+GMvyQKTQ==,type:str]
  FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:elpz5YlmyPK5UsYS32PfTjJGYJC6CMfFTf09tLU5oN2mAVP+ybW35OrYJA==,iv:RYicJs9DR/qADRIeyTgValRIDpJ4JxlubnoA/67MC3E=,tag:tHtYcZ3Gv3Fu77G3V/QWRw==,type:str]
  FORGEJO__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:OcMsGCdMtkJn+45h7XDcT3BNyGWMPjiTEnTZ7mLwQjdn/aNNqGw2a5aoVg==,iv:wj7Zd+dLS4dMz7bi4nKyuqUt290QEb2oMBoMTp1Ru4M=,tag:9WLVpx55Kow3M+tlIuBUCg==,type:str]
  #ENC[AES256_GCM,data:xodgCa57AN6XuRxWKab2xTbo0vZI7HXS5UUDiuO8CPTfVfxcVvwjNtiSqjL/KUlu9ZBxcvYqME9dwvhFCBJh4A==,iv:KDhkhUCqvIsEyAVIkZ2uIty+uvXOcVltOuQOuLs39gQ=,tag:nmEUuycM1MBKHffgazla4Q==,type:comment]
  FORGEJO__storage__MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:Uv/c3sq+GITc37IamzosuwdnTkMzAmWpfe8=,iv:4s/qa6zJ6x4widn8plauFCA9ZReVpgJQNpnjAtmg46Y=,tag:NvAdLjt4iOHanZDT95bBxA==,type:str]
  FORGEJO__storage__MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/qUjyqFdnrU893TCkYwweojDXsUV+RL+G3rmoJWZyOjFBRZYIXGty0lUb56qkyEs0D1R+ff8IJjYj0CJxIS2VA==,iv:kDs3hpsCvLTe94AiBRFuk5CceZEHZoV9pa704ABcz+A=,tag:Gu90V5m5Bt4fkGOCXAHpzA==,type:str]
  #ENC[AES256_GCM,data:0bYO5dwY9Crd/BVZLXirawWGFw8QFoFMbKzJFCg/n/Q=,iv:M57hQWqOn+4KbQ8hGSdr25uPqwdh8oWbrTnoBp3ZSfg=,tag:330fdydHTh7bDXgKk6QJzw==,type:comment]
  FORGEJO__mailer__USER: ENC[AES256_GCM,data:NO0JmSx8PDzFmaLm52BaYr9g6e2V,iv:Yxt6ggWI3k+In65dm1TUbiGuvHbDXvaVqegjYbhnw7Y=,tag:cD1Pu886Qr4pkBokySyp8w==,type:str]
  FORGEJO__mailer__PASSWD: ENC[AES256_GCM,data:CKeX+YDa9M7wIc55VKelQg==,iv:0MWlI/HdZPQHcnFv06izD6gyXYVQfX8YKnyqC21+oyg=,tag:Wz1W8rr4sNPjD0DoWHVdeA==,type:str]
  FORGEJO__cache__HOST: ENC[AES256_GCM,data:zcLnn7IWfo3B9b6qZ6wTcacTV9wghFUNovgaFXaU1Aql91xo/LrDIB7SGmLWUZSARFau0Ar8TQn4Q5TztY7wohodANHBKmS9Flo=,iv:65J8CHtPPovdLgUi5PKIn51mrynaym9Wq55lityuALI=,tag:I+2MEkH7pYr6d1+rQZR1aA==,type:str]
  FORGEJO__session__PROVIDER_CONFIG: ENC[AES256_GCM,data:9MZlspNsD6j9tA1quA+VSEk2bjqBGGorMjQRj5c/uWnQYoYkFQ05E4RHvN5NQL16KbkgmP227/2asx/mauRfp5RUCjik5Mjy7Gw=,iv:PSRBD05YbaGgLQhP0US/YzpbE/ME1d+0w4Vh3fV52bE=,tag:dq2Puq29LgnRN/MzGh7eAA==,type:str]
  FORGEJO__queue__CONN_STR: ENC[AES256_GCM,data:wPL2VZU0F2dxD3X5jVipqQw3+/CRVQJNH7O/p/qFHpQ/Qh8xKHRZeQ/Ml6wSC5ioQNoyclggEm69kijd3D+/kRrukG0nXyXcj+0=,iv:ECc2zpsgbalwW2Uu8AtL1ksouLCCpmegNnUDMLCGDaM=,tag:/bwH7pHieMP+DA42UWHFJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R3cycWowSGg2QmtKTEpa
        YTRaczdjYU5ZQ0lyVjc0RkZWRCt5Y1lwRUJZCk9Eb3p2U1kxaExzOE5nS29Hc1Ra
        NjM4WkpnNW9yOFBjdU45TXlvTXIvbEUKLS0tIEsrVjNTenplZjFpb0ZTUlFJd1Bu
        ZmJNTjdJV2txdGtMTStjV3FjU3ZJejAKIuIsu8ESnpEWORciiN9wuT93JfNVoWyX
        adpm4Pq7jGfQ4Y+n7yqPA/hPbTE4UpbVjYPI5mANFAv5hvj2zM/ObA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-13T19:59:42Z"
  mac: ENC[AES256_GCM,data:NkxZcLkDcHMM2+j0kK3cagBqzz2x2pyZf8rNXqHli/JxfwGIvCe57pTzRSxSNbblTVWLtYfggcUwGFXssMCDzEvi4PMipnJcjQbOwoQ+oz5MsgOFDU5EQZURTPvJZXSeYTD9+/993vXkzXLVSJrSNrh/usMUBioKIrRL2eAFGLc=,iv:NokWJsXlK6hOuqKRi6IJ0MDdnK2OMlZKZXezz9oEfwQ=,tag:zFJSnxrhR0iEa0m/y+U2vQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
