apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
  namespace: forgejo
stringData:
  #ENC[AES256_GCM,data:HDIf0fzEbCskHkfRTXCXfkLw4Z3SS0lp+tq20aIbFM/+rP39pL3vffqOp6NBmc25kQnVbUHUPF6VLpOqNG1nvv6CHgdlcmN8Qs5+ixRL,iv:2UvCKqU4K4mrpNvlS3XnP6v8kgJzNwogsnzn5CZYaRA=,tag:+gCX8mcFz0r0Xldu9aTZuA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Es52zgDSwg==,iv:T14QIgXA4yLp+6hf4kM+dUbHNWyG9baaMhyJAw+lYgQ=,tag:4Bwus54klOZujiHFUpegCQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:lcGYXo8fmRiZyiCbAI72uvVMyHeJWN9WGpww2f0l6yOxAUBBkZzMMpATbRoZdqye2Q==,iv:Hebb7HXIOiZJJ6i02CD1Qcn7yPc09btrzxUai65hrKI=,tag:/p3fpErx0MR9zwUzfHggGA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:KExX0/npFA==,iv:xEeGXZ4WDxi3alUFCwG0REA0kHUKVOJTw8p9UzEa2S0=,tag:EIvUMs3lNniVWwOP620axg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:aGez52UxCHMjeawc9sznQrTQiLHxWEumBA==,iv:kkyWyz3oVzGvbWeSo7iodaoj+oMHJ4p/CzUAZAVeByo=,tag:mPm0pO+S3dygdpL51Qrnhg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:qJ1dNZONttIcwOa6ODT7A6Jt2u4J+yiuZYs=,iv:B5p0wEUwdSdUA6ceHc5XJTeMlmTV7kfr4mGbyJtJVrI=,tag:FdcNR+STz0DG8S+7UDIbDQ==,type:str]
  #ENC[AES256_GCM,data:4V84SfPz5fso3cGggKGRxbNoPMpk7L0SRCz0FiCc6wH1fRrzUerzvtlNUc8XUuexsGeSL12bhg==,iv:HEw5ymV14jSJxR3cKo2YJHaU4aq+HFIpCNokpH+3Nl0=,tag:CaE//mDooZPg6KtqHtOwRw==,type:comment]
  GITEA__database__PASSWD: ENC[AES256_GCM,data:ZWxi1duD0Huajs9zWqMxVzssow+PcYL6Lw==,iv:9ImLb4xsU/bl4E12vq4ig1ukJoDFH+L+34H+MVhMnmo=,tag:2I8uiFsEGJLcs8Djh2AfCA==,type:str]
  #ENC[AES256_GCM,data:1TrQBEy/KUe71SM7lmV+MPfiwj+RlUdGHLv+b4bDbKnxecYJevycQCfPU0G1SjInjYTQ4jbAuQ4BmxzlB6/rIxyZxGDaE53FYpxVjw==,iv:5QcmXkSf1zTwxc6RbOA0pVlUhUpcaHI8BsQPUmVh2Qc=,tag:/et2PJZjNP6JOsyq38k2cw==,type:comment]
  GITEA__security__SECRET_KEY: ENC[AES256_GCM,data:m6AnOfTem6j+zeZfCRc5fiO8vakNBQMwtWmXSXR2S8t2oRXHEJfPumiTLA==,iv:5ooWAkN2bFMArQ2eqRA/EkFR01W2Uaq9aZNY9+TawAQ=,tag:18oFcGAenJBsfDqDVw6zrg==,type:str]
  GITEA__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:4eD2llx+68K+oUOs51modeCyBlVo3QslYOQt4LI+dylOW+/EUZVoGMLpfoaHHP0fRx27UxL8A7KdDd85eBP52z8WFGe8Xb+blbdu1OFHLgEfLgL4AuuvHok9MzdtQAnPD3Mh0QSLwJyk,iv:QQTqq0AKaz/iNy9wIcRIz6GyQW1pIbK0Q0vgAA2kITs=,tag:92Hl0zOJPXrE/j1YESvhOg==,type:str]
  GITEA__oauth2__JWT_SECRET: ENC[AES256_GCM,data:2fzN8sxFi3n2TtM8sYUQTXSq4XtlbO9xzdzircg/7H6FgWLtAsfw31GwFQ==,iv:+AYFDRFTKNsymnIbBAY4Cms5amJ173eW2OAKmuUG+RU=,tag:GCOk61PYN5g8nEehuip0UQ==,type:str]
  GITEA__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:AqzvhxR73btgUOaMGPt//cPUmOqQ48jyWywhBEfUW0JIInlB7UNVjWgxKA==,iv:hyb64oaKdotXxR/8xA6GQls+fRYNjrBtOWSUX083E4E=,tag:cHGOl1+aiUtUGn8+Z8cbAQ==,type:str]
  #ENC[AES256_GCM,data:JQU8SqZ/7kVP86ujH5DiT03PsXTBXfO1KQmT0c3VZxzNQ5pGR9cgMJXCmkmg8vuNpOLO0KD493yj75epZEYOFg==,iv:InZfjn9lsuNQsG6Czvc08ABXIjifVCrJV7ptW7gB7GA=,tag:1eO23o8+md4jJe0/oyffQg==,type:comment]
  GITEA__storage__MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:eOrSlBas05/yHEMn+sDsU19pNRfrEeM2SU4=,iv:Dq/c8mkUaLnO3XNdO/zesOVAMb3nLRY3vNWrfQPDN5I=,tag:w5CU4lq8M51+da/GqOMtaw==,type:str]
  GITEA__storage__MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PUYscMqrlOrabIGl6hP1qOH33gY73i1TzSoKkoQDLB+bNOjgA0OEXIKr73u/9Aq/D5CgNVGxxHQmcNzQsV/G3w==,iv:dZ2lxJmIZjYVlRk/jKktG3h9Oi8o1yEXi/wu7Xw4/hE=,tag:46p7BFxBsIamyr2P0WR23Q==,type:str]
  #ENC[AES256_GCM,data:fNhVdgGxsiqLwIFNFZCBsf9a58QXnIhRqXNwbcnM2q0=,iv:bTZCP6h7cXrgO+aDf5WNsFy+3AST5rQfM8IkeSmDbj8=,tag:J/xLoGX5vEcfc3wH7h788Q==,type:comment]
  GITEA__mailer__USER: ENC[AES256_GCM,data:8IVigzZ4FR3WM+IQ8tdm8knUXzOj,iv:3n4KjcT1p3A0TROh/jaoj4Yzd5KdZA4sGEAJcSNVV4Q=,tag:u16JMV1j2PFOTdxfBHChBA==,type:str]
  GITEA__mailer__PASSWD: ENC[AES256_GCM,data:AKU9tCAP2bgLf8nJnG0oDQ==,iv:zVFmjNt+qXjWHZC+C4BOtkoef+niFTlKvUNLcG+3qoE=,tag:xPq3PJpZRke3rOL12nVVGA==,type:str]
  GITEA__cache__HOST: ENC[AES256_GCM,data:b8paYcSX4Btuuy8dnxzIqxlQVf/3p25ytsmHakCcQU9WYl4ERjQlEiCSfoMpwvHR4WZ3MSXkoGSJRuR7Oe0Lrhkn7Dos3Lw4SFs=,iv:Rqg2qYhqdUJdC6aY4NpB+Vy2mdSb5gABJP9uO0uKvuU=,tag:Yg3Y4bP4WhRLMhzDjsB8uA==,type:str]
  GITEA__session__PROVIDER_CONFIG: ENC[AES256_GCM,data:RwbIQrOTU5FMh4S1mVYKx1lu80gB/cIoOvm8yHhKYliu9isFowxMjxOsL7cOrcxoepCmqPts2CQTFEAFscQoDQWZOjXPwUpOCwA=,iv:pxzCrNH5C1/MACc9rDNiNRoFVfUndJU8BJl2B+3jj4M=,tag:lcKYHDqqxCC95FWSwW/wAg==,type:str]
  GITEA__queue__CONN_STR: ENC[AES256_GCM,data:Jol2tJYkDSVToTcnkkVs3i+PB8DVB+T/YZe8Y5VTcp/ms/pnSHM9UVaf5aApB9FEI4y/MkcGtTOxsk9WMXQ7ZJgH6iFFw7ZxH7M=,iv:QKhCVgQFOkot+ovt7kAJlIdci+WrWB6WJmjX/9fTqho=,tag:S62gO/mSsL1vSEYkDkF4vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVGZqZXhrKzd2Y09Eb2h5
        ckVRc2dBQktWT1MrK29DdnFnS3JZcFlmOXg0CjhPeWMzaWxjeGZKSWZqYm5zNDVa
        cjFsT3JVS0srV3krV2hYNURIOFQ2aXcKLS0tIFBUcTdPQzl4UE8zeFFIWllkVEVW
        aUZSdURyZHI1eTljQkY2dWVoNU5QaGsK3Ky4M/ujwwmBtDIJsOsRjMsJ8+lysKGJ
        TaCobJsLhvVmq8TRYfSHZnqEP+XINIvsZabu6f5dB6ZbaOe39lbhkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-13T17:08:41Z"
  mac: ENC[AES256_GCM,data:aXLHtgie5+nxcfsBCfcfcWlhNRIGXIkhqDLQPNwCXo/5XQ08+Dn1GBIsbdr900krlG0Ilo8+Pa4vaHPDrw+e74hpnnUcI5ArDpyvQX0UbitPGVxKepz6FuOJEdvMIkEpc3v+c1nc9pa8EiDikPspCZDy/UWyWOeHJiwMN3vVwIY=,iv:OVfCkOFOCwrm0nf4KCj5c3Zm5RrOfh49SjfDWiXgFvg=,tag:56wt+80HN1E4J0askQe+qA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
