apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-exporter
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/observability/adguard-exporter
      targetRevision: main
      ref: adguard-exporter-repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 5.2.1
      helm:
        releaseName: adguard-exporter
        valueFiles:
          - $adguard-exporter-repo/kubernetes/apps/observability/adguard-exporter/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
