apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ruby-echo
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/ruby-echo/ruby-echo
      targetRevision: main
      ref: ruby-echo-repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 5.0.1
      helm:
        releaseName: ruby-echo
        valueFiles:
          - $ruby-echo-repo/kubernetes/apps/ruby-echo/ruby-echo/values.yaml
  destination:
    name: in-cluster
    namespace: ruby-echo
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
