apiVersion: v1
kind: Secret
metadata:
  name: bothy-ghcr-pull
  namespace: bothy
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:5zfK/w62aYT7N1yD0AK8SbIbO9RBL2y1CxWvB2mixjLMa8Ybszxm0xKEvRDArX6hnBDFEUEQXXZYjjIKhD5FaJdC3q0EFAtN49waGuWabuJlOtqXo+bXkjO6DulK47l4+RDm/axbdIMPyjNc2G/RIrNgJNgRBfFrc2nX4Go1UiuWWtgGootZGxUyfbVGK5TAIIs/RKuAoSVGuRiXMxYsQhreMKp8nM46109DCw==,iv:QV4DRIz+DoTuPSt0TVefODpnVwSnLw2X+CY41pGbeV0=,tag:T2rGjmNXrezczg4sVJj+mA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZEdoZ3BtZ3VXY0tQMU55
        VnA2elFvYWJMSFk1QWIweUZ3aWVoUVRoWXlzCmtkODI0TWNUQm1Vdi9UcmxjNTdE
        M1N3alJZSXJxNkV0dGFmY0tmcTZBK0kKLS0tIGc0Qy9rcldxZmRqTXFwS2ordUdz
        U0VFYVhreTdhSmJITnhncFpXaklKalkKHf+2Np/43NsOjeiUxnLo2A+LE/oJyPRl
        58731igIIeoBpSpRV/7b/ercLhns9y2v+Fgc+Lmx7oVIhIzHQ24YEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T01:34:05Z"
  mac: ENC[AES256_GCM,data:1EKg1FJqBMBMyVA+L/V8pc1E95oQizlDSR+zWrrhvM44Pts4eO4JT356XQ+2X55buDVnf2TH9sa1kag1OPfg51Q1Wq0dcy+VyfmztVaqmMTlXgcxKvZGNyCPkkaAiL0xVw4JiD+iRAR4aYVFWmN1knqrIpLihxc0015q4hwnBvA=,iv:caUbi8rV3UuCXsci+n2EHNIl0orEODkG7hKO+nC3KqI=,tag:8BJCUcJeUDyEPDK44UzRjg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
