apiVersion: v1
kind: Secret
metadata:
  name: bothy-secret
  namespace: bothy
stringData:
  BOTHY_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MfvlNxPFGUa/FOii8XKx6f1OX0oZXABdNHLMGSNL/n+Az6OxLEEs1db4T7xzSPBPYR5SfcrWa7yWPb/iHDIJ6mUeHcCMqpy1,iv:0qBAYQehwNzDeVGmAiDr/egItLShp4aqSC16mORwR94=,tag:b26Uut+o/WNmW1YUoYCVPA==,type:str]
  BOTHY_SESSION_KEY: ENC[AES256_GCM,data:UuF7swL9IuvOnMZcIV0cWJous+p7RArrnumgMR1bYJvvCtqVYC6RZZrD0s7h1ph7XuB3a3957AP+56ahyO7M4xxpdYTUSS9wENo91rxGniA/fjshiN1E/A==,iv:dyR3WbACN0XhisgfBWsu0vpUpPHPXsgTaRECOkN64d4=,tag:ZUHai/2UxUWlQ7IJet4JdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTEpNNXFITWZ5N05NUGJL
        ZE80RUFLTVlKV2V6U0Y1Q1V0M0dsZUFDOFRZCkNjOFh4ZDExeEdaQ0VSaysrOUM0
        VTRiL016cGFtaE5pZU5ZZll5dGdnamMKLS0tIHJyOUNFMXkrNDFPejd5VjA2Z29p
        M3YvN1lsTjczcHB2NFQ3OEJqTmRodWcK69Kt2M789vLUK2YYG70bsjrscIsQS4a5
        yAqYRyH1l9z0ceRuH8UkDQAK7aEPykiQJFCuveWAvYRiQHXOYl8z4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-11T04:30:52Z"
  mac: ENC[AES256_GCM,data:Sw6+3xBjRhL4MdHjjYMAAL9K0gzCjhvc+Y+lSDQ21R3klDOsi4suRlBgXfkQo5AfDT+qpZu7a1lgmlv4G/Z4IbayQ1Al4ZwHAEOx6wSx9ro7UIoY/Qddd+2wzv6K1WJn7kbUR5jOWoi75Lt0oFG1sJqsqkK4JaHXi68LbU5SGfs=,iv:oudi4p6VFNNC4xlDFCMi7Mltvv+nM5JFRrKI52hofFI=,tag:lxcHqqBChP+zxo9PlBT/lg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
