apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-metrics
stringData:
  token: ENC[AES256_GCM,data:2jThvHbyvVEUSQsNwTHuuCm5VwXkJwKZZTX/19n2RvL9/TFJC7qrN/j+Sdk1L/FNT+RDIQ1ykaet7XHTib9UylNUKIreLdPh50/2X3CIUjv64pGddP5cj1uG4JV8WXPU0GsOLiOAw2b6q7MgqUU8rgmLMaBW8bc0mHe8ujJ/2belS2M4W5CtneeivObpYILjmKlQf86z4Nqhb51Nzrn2GE/7n9WFdRUeChoJS8B6U6BxIp//rmcc,iv:ShBwZuHdTYM7Fn4B8OZLvgnkqQxATd9EOcKaaIGzlAM=,tag:U9jKtnK8MBDRRKq32qu8OQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU3RTQ1FWaTc2aGpNTHFv
        cXJhMzdJb082dFlRYitLQm5sWk1wTlFtblhVCmtmR0FqdmNMU0ZkL2Z0djFrQll3
        TENBWm1na0J5S0tuUFkyVXJyZldiUTgKLS0tIEpNM3YrcnZza1BjOVloYWF4by92
        eGhQWWRaMGd1aG5ZNFBpMTJLZjZTYWsKN0nwR+sZKXCetyUbKHchIUGaAknxN75g
        WgUrnUmOCSCZfM9ihmN2PYGnGjc1GwEBHp+mTP4ik6tnh+5AKMh2vg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T16:35:45Z"
  mac: ENC[AES256_GCM,data:LmQ0gpBW9zWfeuF+ML2FLzWwHpDqJXh8VofO3T128lP6LKnOEcltT4HJUNVTMdHClG2TZimZSQfFlUBct/F4n6l/od81z66+cxQvvIuhyYDM42qdXFh4rqZPYou2oMPK6KLSwuvaqomi1iJi61+5ZnYwAbrBKK04kKsvh21j8qM=,iv:kgM0CXOtQhGwfT7BzrKm/6YTvAiEzAl3iPOKs+hrcwk=,tag:+iHmVFmiQTMvi98XpaljPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
