apiVersion: v1
kind: Secret
metadata:
  name: tuwunel-secret
  namespace: matrix
stringData:
  #ENC[AES256_GCM,data:eS6vHyGYBISPA6J86bpNPn3wGZowRdC8DFlGQWPkebmkG5i8bPaeXIq4Lq5YPn8+av0/iTj9iFphiwZG2+puWK0T8HHI7LghfTz6,iv:F9toWY6uJ7kxnst/nJCgG+pg2NOPYBNfZwvYg0hayOY=,tag:kDBGCVuZm/W9uHnrIF4ndg==,type:comment]
  #ENC[AES256_GCM,data:lmpgBBEC0LR8bJ2iaZZjRw9l9WmJm2UQNtD8DXJaftirjoguJ9rDmEeklw8tpYs93FteoHSi3xcGFHkwev2++VaqTQbCl7sS0g==,iv:PMGjzWJv1Lif+zESJkOtB9RcxHdoXCoqIXOoB31gtgE=,tag:71GjKCrnsTbMl+e220PrFw==,type:comment]
  TUWUNEL_REGISTRATION_TOKEN: ENC[AES256_GCM,data:WvxyD2UOgmAVvNYMSI+eJFDvVia3Y3BMscy0n3XdheVdIc44gbvyW3/8CuOlTyEW,iv:dCF7S6sar1aIVHG3XJkdAq7PvnUQvMmfRPwZbre534g=,tag:K7XnsvA/FoWTRph/OdvXlw==,type:str]
  #ENC[AES256_GCM,data:pHTULycR1sEyMK6FnvQ4o2BQrn1lwMKrofLYmk02FZ9eH/PdTsXyvgtSGTSfRxpz/mFLkJpoxKnxEfTTcw==,iv:2jIsQGMTyuSt+IAWc3RinQSD+QUi8I51YCBrAJBXcmg=,tag:0ZU9vtB2FgG8FgcGXhqAFw==,type:comment]
  TUWUNEL_IDENTITY_PROVIDER__0__CLIENT_SECRET: ENC[AES256_GCM,data:h76whyZq+Zv6+hVYj+XVJ/xeCOHya23JOXP81iJ5RyOn3hzrSS1WGR6aikVGu7s6JXtmqWg3YiDFhimCYEt1pdJJmiGewEP0,iv:7zCw79TsvSInyGngqcmt/GrK5IXG2SpRQAnft46rACk=,tag:Rl3AMZyw5w7KGS10/2Ituw==,type:str]
  #ENC[AES256_GCM,data:zDHiUdT+C/EXIW8O8BAJBSNQe3i2iFZrJGZr6B+eLEDRwWwd52SPNBWoDHs=,iv:NEbma9b5bmJ8chtk9oKs62cni1OhD1NUnDxhYZM4/vU=,tag:zo922F4TLIMSWGueDXoE0w==,type:comment]
  TUWUNEL_STORAGE_PROVIDER__GARAGE__S3__KEY: ENC[AES256_GCM,data:0Lg+lKtGnWQP3b/+Yo/Ihxs/nZNlMtzMcqQ=,iv:NK2psjLU+uA7MFT9M3WRt3xp+RkX7NXUd7V+HwvU5/4=,tag:F/Dp+GoNyk18tUFjS68A9w==,type:str]
  TUWUNEL_STORAGE_PROVIDER__GARAGE__S3__SECRET: ENC[AES256_GCM,data:HCx8uHjj8iFmdyaYhwZU4A0aRGsQarw28SG/Q3uCkzDLQkr/NE7t9hvlnYdra6o/JM5rulk90mUwwDXsgoT4/w==,iv:TxsNWVhVT94u5ulZDwvv30o4ii/zC8chGFAsiNLcCzY=,tag:y9pIrrziN6CiKX0vtmI9/w==,type:str]
  TUWUNEL_OIDC_REGISTRATION_ACCESS_TOKEN: ENC[AES256_GCM,data:AfKXrbnzebu4O6pSOZMLifbInTJcCMkch40+DywS494jEyrT1RTgm262pyDGL06A1K0uSdY8yHJrEtFnyI/K5A==,iv:99eaOi+ey2m0FwKgwa7wXjbMXaKgJ2IOaqxvw0L4Tlw=,tag:dGUow9CedvZNg6/L3544Ew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWnBCWk9NQ1hFUTMvUlk1
        MGlEMllibjAxa01TSzVzclBzSkY1a2JsWTNJCjZZRW9DTFZSZjRwOXFPTU9iVTJB
        bVVTYXFIRVBMTkc2ajZTdTVHOTRtelEKLS0tIHBkRE1LSllVSVNIYkluSjl2ZStJ
        RUFiWXVVSDVSOWx3TlU3N3B3dXdmRGsKY+AvqgARjjOh0CxzYKiK//m5jxYrerCw
        KqjZ4TIyWViCY9iWn3+9pNKMJalqMtSRue06+DEUJuWmASKNVlwrNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T18:32:45Z"
  mac: ENC[AES256_GCM,data:/O/cGXA6DuNrzKiEoWDRl3vpXCUwmK/iznPEQOk8Che2cmfvVaeUGk+uZ4izwuFzi5tIPnehoJgl7+jv88Ka0XUhoy5EIZDe3jfnDtfaiAzxnpp08Lmaaky24SfP/MnzuYDRUpBNJ/fnO3QmiXc5bMBkI2mj3YdAys2Z53um7Jk=,iv:N+B7CmXvdK0f4FAAK6oITzYW9o1xYwNlRPFuNM53NvI=,tag:wRwMicR63jE770qd8odqDw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
