apiVersion: v1
kind: Secret
metadata:
  name: lubelog-secret
  namespace: lubelog
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5+7/xNfWQA==,iv:CHbAPZK8djS6F0cZXamuZfX50xfFmNzyd6xShCB4kfQ=,tag:3jr8IdK9VWPI6Y+Zs6Ml+Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tufyLOuvxFTgEwG9J9olBtVQHoWarbxPQN2JCesiwsCOOY+deKv2HuTc0ZCPkoatMQ==,iv:oT/eUAz7yMVzFf/dy5hOT5RkUCyUn/6G5wbrxQEl/Xs=,tag:WcqW71jX93VL2ePGKgiZtA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:CvlgapDr0Q==,iv:m+utp23k/LpieYVlpWnMCwLMuHWi/WYqFOT+dOJ4IVw=,tag:TGTXodjbpeZ8NTAgGsYuKQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:cbJcTep81juYIiPC0m4uVQoq/BJPU9Caveg43ws=,iv:5YUYW9OG1F6enbkw56qNqoZvHxCaBxjkerq0kfuoFBM=,tag:ifAxffwJpGQoEsSwPyP+Sg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:usPMgP7nQOBPp/uez9I+pb9reciqcYnf3fM=,iv:drVmSn+tqti4iG9LYqYQ2OqhVF0sMxrepPhah8LjXS0=,tag:oitr2ixoLybI9wvyjE00ig==,type:str]
  POSTGRES_CONNECTION: ENC[AES256_GCM,data:Oo/n2j7HpvrSuOV31I7ccMMnPDzsQlXKzlwBJ81S2ktnWAxM61U8rUMI0z9m2RwjOXqH0nwuJWVlDfYE8oEDVgUqaW+fcShgKo3Ioqo8ULhu31gPi283LkYRMduy/EdtJ15NJAtrmsSfO6CC4neadb2VkeZPmL9sNahC0SBg5Qmd+W4M,iv:6ungOk5iGWk6aO2ZRdYiidIBBRTDuOHV0RiRXejyIR0=,tag:tOpJgJ2qhD2eImDD0VLuqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTEFsNStiTjlybHpHanN6
        NzVjUTBkM2htSUJRZUd1cXZQMWJEU3dzOFVFCm9JRXBuL2UxSEQ2TkcwRTQ5VUpB
        SHQrM0VJWFZZNk1oaldIRjFKMEY1M0kKLS0tIEhFejRLNm9wcnFwOE91LzRaeUxU
        UWRqVTBLS0JGV0c4TXhBaXZZOVUxU2MKG9WnIGa5K51ab4t4r9arCuHRI/hsnUck
        YKpaKzYWYXHg8LpHnDHqT1izBldGK28p3b6N+wdp6bLIuVa3n7kPEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T00:09:07Z"
  mac: ENC[AES256_GCM,data:6ANayfrQZ2ITjQrCt1djOrTQZw85sdcjs6mSziAI06nNigDqIgWb7GjC+Zkj5aisNtGkHXs/Pa7b4x3ZZwylt6rRxeJr9Ui5oJE/4PO26lhvhj4zamNpJyFaBE9Vn9FBciSGV7pz/5+eE7gTJN7TlWunvu5UUuJ77IX3Ln788x0=,iv:g+bmXwMG5PDkjso+fqsBKJGjohaJITfKPAjqsm0zC9E=,tag:Kh3RrheUN6GhiS/rbk+i1g==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
