---
namespaceOverride: database
image:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud
  # changelog: GH releases cloudnative-pg/plugin-barman-cloud (not in PR body)
  tag: v0.14.0@sha256:823a8893690980ba5830bbbb11196a35f695b0488db7d846abc33baebf32417c
sidecarImage:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud-sidecar
  # changelog: GH releases cloudnative-pg/plugin-barman-cloud (not in PR body)
  tag: v0.13.0@sha256:990361af3319f9e23aafa0f6d7981f99bf1f69b4e6a85cf1bc7d71d6f09bb288
