---
namespaceOverride: database
image:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud
  # changelog: GH releases cloudnative-pg/plugin-barman-cloud (not in PR body)
  tag: v0.13.0@sha256:71589dbac582333442812b07b31f7ea4d00324a8358aac7ca507dabf9f4b6c96
sidecarImage:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud-sidecar
  # changelog: GH releases cloudnative-pg/plugin-barman-cloud (not in PR body)
  tag: v0.14.0@sha256:9880817c285c7afa4d195da2145064d21907405489ed6ec39abe59b1feb558a4
