---
namespaceOverride: database
image:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud
  # changelog: GH releases cloudnative-pg/plugin-barman-cloud (not in PR body)
  tag: v0.14.0@sha256:823a8893690980ba5830bbbb11196a35f695b0488db7d846abc33baebf32417c
sidecarImage:
  registry: ghcr.io
  repository: cloudnative-pg/plugin-barman-cloud-sidecar
  # changelog: GH releases cloudnative-pg/plugin-barman-cloud (not in PR body)
  tag: v0.14.0@sha256:9880817c285c7afa4d195da2145064d21907405489ed6ec39abe59b1feb558a4
