apiVersion: v1
kind: Secret
metadata:
  name: reckage-secret
  namespace: reckage
stringData:
  #ENC[AES256_GCM,data:u2W9hvGzmbHLfJIGgVpzTySsGtbZgXSPP4NTD3ikW8ABpbSZ/J4yGqdqQaXYDTl6R0DepTkBGX/zh8xa7mirvxC8S9EH,iv:BY2sjz6t9SScI7xn+0dbmuMVU6pYtKyCStaPHYOcZck=,tag:UJbnz2IlK6yW+zzoxA4sVg==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:PjwteAM/RL4KySsQHCOsratrDckFeuvL4epThTN5m3XKiCRR8EK/BLs2K7UigpBaAw==,iv:up0D52/cbAjj8PwJfoFhDxqm1QAmXiTbqhTOI5l2hcI=,tag:1u7V0cDZlth46XkKUILS2Q==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jO4NbeFzgQ==,iv:sqrUKL7ZxdTnIdibRWmy8/79dz50e4FMhHQZU8Emkc8=,tag:klo83dgtTxWPDfDmAJeDww==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:DV9v9CNDlQ==,iv:b3zGCcJ0CT2Ok7UBfyYEAjLfETs2Ad9RAhgiH4kqiXQ=,tag:sh7D8wZfBCcRkWOSN0PQfw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SyQBc+ML19KheYpJ6uBwidx/mIBBtVIc922NUlmdbw==,iv:y2ASdD62DPXc9smckjqM2EfyOXml9vVnXwQBl1PVC+4=,tag:82J/7+vJQAVbwyfs7l94vw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xGtfxGeyZi68zinjkH6ZIUe9+Nxfs4nIu4I=,iv:zNATbFDpugdtdqVDpDmLph/EQ9rpbsGM+f2XOdPczFw=,tag:VfVgvquzAeExsXqVqNDTdA==,type:str]
  #ENC[AES256_GCM,data:4hGxjj0zdOhxoCWBxX13dNPq6K98kK2YCwEPfxylvf8IdPENeRDMyxyBCkrTqS5rfGlOfxd7+WsAUuEFlscci7rpj2g=,iv:RihosIBSfFMQiyhMjf+Zi9DNpkIZ5BmwOzj4qMyd6V0=,tag:jKVldlDJoy2dxvP3Bka7/A==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:Up1y3i6LBeDoVRcaiuyn/d3D0wqZti5+xRuRm749iYiXHAlYDjdNDwma/uHvx212jwx768aFrmlQcs3RrQW9WHbzcQjxFqMUt0bqGZTdfSB0I8XXlAgawtX+wWT+gtsBPfyEOynXxWA9oqu1rACQuZVWBnXB8BYGieK87zKp0287,iv:0/W2w9cjyTyPSrHq2P9SFIo69ab6wgc4PxM/pLzA7jc=,tag:TXzLNCoFaBucg04dX2ycuQ==,type:str]
  #ENC[AES256_GCM,data:pH2ItZJ++/CyB8cAQvXrUkZIxKQqPOsuyxXGyiPYfLiXTRLycXxTEdtIatw=,iv:VoQbPsYbGBHXq1Wcl2G5qkimZozIdyEIJbFzIRV22Os=,tag:9ziqOf2xUwlYLUEoiFy/gA==,type:comment]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0oa80d+6g//RBHe+UCCFUD1JSdoPFv0E+BPk61qSR+pIRkb+foNFkGe8GB6Uv3EKThoQot4BrIWEo1P9BSxjlK/xV+nixAJ0,iv:ua/VpIYNclzEotRBkC59dcS8cZFkJMT9bVBzF6cmEeM=,tag:gAFkDUfezTO5cw3D2B+dbQ==,type:str]
  #ENC[AES256_GCM,data:CO+26w3gCtiDHf13mmMOG1Pz4x2foqN3pGztwDgKX6UMWqYmZ3QA+lK2PWyLWL4XSoEjmLzlnnG45YY=,iv:Q8JSY7GiW7Ew0Vzz2urYLHCUULVu0AbescQXQ8XczhM=,tag:51kWlcqMRFqHXIJcrChx2w==,type:comment]
  TMDB_TOKEN: ENC[AES256_GCM,data:vLP/rfbzNmq1uNbgL2sSd/QgtruBUMEiqzVp9N+jZrVyg0dmpFzZSAt726qp3Rd+/0yUuFjYf+rh0h0e7Q2sDSR2BWf/LSSwXoxX0WcLf82wFv69iPSEHMg0d1KQoooVGiPRnulY3/IFE30OJGmwKzKKcUESxffJFW4AKcjcUg08ztmv5wA0tJGrEl4Tey29+6wg4ImgFV6jPoNOkxxn6VfXnFhSkS7H5Hu3WP7X/KrPWivZIbjWBMo0IOo2PdIsFyI+AlnASIMZViGQFatvWeUnsclmo8ecofpfNz4OjP+tIlx8wAC1lSwLXp3QRTM=,iv:QdbBeQxvBcOUL4YIyGFWMSCx7eD62I9//8UOgFG1kww=,tag:vGJlZcYOgGRTN72KtWbLvg==,type:str]
  GOOGLE_BOOKS_API_KEY: ENC[AES256_GCM,data:lFiiP6zVSD2jtLZ2iTSrCNa6TpjE7wKfbLwpf8v1TNzSWpDp4sC/,iv:65LRExyoLCPvGQln3YWDDsZGt0uDmI6K0ce0wMnwsGg=,tag:D8pC2NB0DCB6i7Mgvl5vsQ==,type:str]
  IGDB_CLIENT_ID: ENC[AES256_GCM,data:i7mMzUJ6ij7EWRxa+bS2m8JiUkdwNgBqwfUUK7Qy,iv:Rq55hku0z5BmUWm8779QF98D7S+yIkQPqsumNu2/yRY=,tag:Uffo1tOAVBIWNJKhfSBgdQ==,type:str]
  IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:V2vq1VbMV2LzywKFn19T+sfLclfwQhtbYZ5XGTTN,iv:pGeMqYO09GyjDeZEbWsiNfI27PPS4LEorypMOm4N/9k=,tag:o8c6KZdHfmaXVzCVyf+ddQ==,type:str]
  BGG_TOKEN: ENC[AES256_GCM,data:uvSP084Rx6sIQU6I2E/oioJ/D6ZqHg93lomHmBegJjUj3FQ4,iv:4uFio6s28e0L8PBGbL3RgqhMnvSyK2HJo1eNQceYybU=,tag:8BLMQtxNIhPAt+PlZCkqLA==,type:str]
  PODCAST_INDEX_KEY: ENC[AES256_GCM,data:U1XejZCcaMlHpY0EqkrncLOuPc4=,iv:OYFAW/xnyxMDz9jksu+Vrlwdr8r2ywdnVSKp4ww88h0=,tag:KVPjGa78Jw8uwyLr+qSPHw==,type:str]
  PODCAST_INDEX_SECRET: ENC[AES256_GCM,data:cISLikurdJSa1lykmseu1Rmscgo0CSRk+kHXCnRUU+wy5pd1PqXW9w==,iv:bJ+0Wm0jqK2+oVb4JvDYTeaI9vWpbHsJiwOKK2z6Q2I=,tag:M+KyfWTDvLW4x25wwFta2A==,type:str]
  #ENC[AES256_GCM,data:CiXrC4eIcKtyTzmEGtwT5XuuVA45z0dTkQ/+wLQGO6xunZR7TUvNTNR7MYSZqRpu0c7P0uRT4mv4jKeVcWiU1SKQFU4FXJD/5HoKkwg6+aSSpDKQ,iv:WGuGIfTcLiT+6A0/IoMfrmVvY4vhIIvc3K+hPn1ursQ=,tag:ar/2Am5jSvN1WBZUFyci4A==,type:comment]
  PUSHOVER_APP_TOKEN: ""
  PUSHOVER_USER_KEY: ""
  PUSHOVER_DEVICE: ""
  PUSHOVER_SOUND: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUEJLV1ZnTTZmWlpVVEV0
        VGpUQUZ4UnNZSEtSLyt2ZndNK3AvWi85OFRnClhIV3JnWjFYS2ppMjJQdWo5QXgr
        QUFiaVZJWDFjYjlnUElZaVN1TEp2ZTAKLS0tIGNqNFNoWTB4S05UWUw4NEVKdDgw
        MlBzdzZRVjRvNittaHIyL3hyeDNseEkK46PugkSORyPIgREexqjZh6E8OPYs61jP
        avFwIz7P1yyRPkhPHezWkXlZ6/Ip8CBFWUrdhUEXGma+3G0MnyCDJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T20:56:43Z"
  mac: ENC[AES256_GCM,data:64kia+ntiCaL9Wz0R14UyMg/nCydupNnlLEWjanTCN6taYrw0TwTg02lwGQ0S0iG3c398+Ir8trPnF/srlZ3T4v+SnGvEVEoxHkwgsnMvnssr8zmLAgCOScfY2dCOe7KxK+StjIQ2IuDqhIV8y1S64DEk3pLQnYkCTH3R3gt+4w=,iv:R3JlbQMYdipeyCEuoolKHLgw/kUqZPjhAhNEqwTHWAk=,tag:naEZeeH6ZA87O7N3W4GbtA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
