apiVersion: v1
kind: Secret
metadata:
  name: reckage-secret
  namespace: reckage
stringData:
  #ENC[AES256_GCM,data:u2W9hvGzmbHLfJIGgVpzTySsGtbZgXSPP4NTD3ikW8ABpbSZ/J4yGqdqQaXYDTl6R0DepTkBGX/zh8xa7mirvxC8S9EH,iv:BY2sjz6t9SScI7xn+0dbmuMVU6pYtKyCStaPHYOcZck=,tag:UJbnz2IlK6yW+zzoxA4sVg==,type:comment]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:PjwteAM/RL4KySsQHCOsratrDckFeuvL4epThTN5m3XKiCRR8EK/BLs2K7UigpBaAw==,iv:up0D52/cbAjj8PwJfoFhDxqm1QAmXiTbqhTOI5l2hcI=,tag:1u7V0cDZlth46XkKUILS2Q==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:jO4NbeFzgQ==,iv:sqrUKL7ZxdTnIdibRWmy8/79dz50e4FMhHQZU8Emkc8=,tag:klo83dgtTxWPDfDmAJeDww==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:DV9v9CNDlQ==,iv:b3zGCcJ0CT2Ok7UBfyYEAjLfETs2Ad9RAhgiH4kqiXQ=,tag:sh7D8wZfBCcRkWOSN0PQfw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:V6GD1443uRifGcbbOwD6fnDWmSR95MGc,iv:5TBItH5DhpFmKjkkZTaWzMnWaYDQfD0RiF0hT6HiITg=,tag:jDmevT3tFR5aXpIaavKZMw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:IYgjHZ+6GZ/XyQXBcsb6cYJFr/IxbMdmPGs0Cg==,iv:BVDpCqh3xa4/1b1riGrBwAE+MMD3WyHHysdL4io0V38=,tag:eWDy4hCdsqUXH2epDC3NWA==,type:str]
  #ENC[AES256_GCM,data:4hGxjj0zdOhxoCWBxX13dNPq6K98kK2YCwEPfxylvf8IdPENeRDMyxyBCkrTqS5rfGlOfxd7+WsAUuEFlscci7rpj2g=,iv:RihosIBSfFMQiyhMjf+Zi9DNpkIZ5BmwOzj4qMyd6V0=,tag:jKVldlDJoy2dxvP3Bka7/A==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:AacfhJURtwiSuEckW2rE5snoSY0d+9Ah8rcHFDMzLts9LMj1yKt1Kh83EiM9B9MRL9JPnoVdDAoHs5MeIQqO6NA++V8QXik6nnuwWKOkVuv4qKDLEOORQImKOXS9VNcHLkWdAepVIOnNQMJUNw0/UHG7uJisveBxAk0=,iv:mwBqTdr2s+SS5hHEYszxnc1HUtPTvHqBHSCcsuDBwRk=,tag:BDcfQAI1XRP4wiUSQ75mjQ==,type:str]
  #ENC[AES256_GCM,data:pH2ItZJ++/CyB8cAQvXrUkZIxKQqPOsuyxXGyiPYfLiXTRLycXxTEdtIatw=,iv:VoQbPsYbGBHXq1Wcl2G5qkimZozIdyEIJbFzIRV22Os=,tag:9ziqOf2xUwlYLUEoiFy/gA==,type:comment]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:tfHozezEL+H/VVq/0bjQTdeQ/gEzhqRtmh8Q,iv:XHuaIMca5ZBcv2F7DJTKEw/Qf0x8m+dnxYbLOhNp/AA=,tag:m9teJDqyAzYj1z90/PrKMw==,type:str]
  #ENC[AES256_GCM,data:CO+26w3gCtiDHf13mmMOG1Pz4x2foqN3pGztwDgKX6UMWqYmZ3QA+lK2PWyLWL4XSoEjmLzlnnG45YY=,iv:Q8JSY7GiW7Ew0Vzz2urYLHCUULVu0AbescQXQ8XczhM=,tag:51kWlcqMRFqHXIJcrChx2w==,type:comment]
  TMDB_TOKEN: ""
  GOOGLE_BOOKS_API_KEY: ""
  IGDB_CLIENT_ID: ""
  IGDB_CLIENT_SECRET: ""
  BGG_TOKEN: ""
  PODCAST_INDEX_KEY: ""
  PODCAST_INDEX_SECRET: ""
  #ENC[AES256_GCM,data:CiXrC4eIcKtyTzmEGtwT5XuuVA45z0dTkQ/+wLQGO6xunZR7TUvNTNR7MYSZqRpu0c7P0uRT4mv4jKeVcWiU1SKQFU4FXJD/5HoKkwg6+aSSpDKQ,iv:WGuGIfTcLiT+6A0/IoMfrmVvY4vhIIvc3K+hPn1ursQ=,tag:ar/2Am5jSvN1WBZUFyci4A==,type:comment]
  PUSHOVER_APP_TOKEN: ""
  PUSHOVER_USER_KEY: ""
  PUSHOVER_DEVICE: ""
  PUSHOVER_SOUND: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUEJLV1ZnTTZmWlpVVEV0
        VGpUQUZ4UnNZSEtSLyt2ZndNK3AvWi85OFRnClhIV3JnWjFYS2ppMjJQdWo5QXgr
        QUFiaVZJWDFjYjlnUElZaVN1TEp2ZTAKLS0tIGNqNFNoWTB4S05UWUw4NEVKdDgw
        MlBzdzZRVjRvNittaHIyL3hyeDNseEkK46PugkSORyPIgREexqjZh6E8OPYs61jP
        avFwIz7P1yyRPkhPHezWkXlZ6/Ip8CBFWUrdhUEXGma+3G0MnyCDJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T20:46:43Z"
  mac: ENC[AES256_GCM,data:HXrqLJjtdfA27pC1OVpdBEMHY+4lEXbxP+7/NLp98muH6irVWUoaXTrUbMn2nrQ6li7n+sVlwmEKNAAh+hUgQsfi+iRgze+8TIAEjSucGq/GTMIuR1PjgQyxre8GV0wH9SQjhVcdZjg4gMmIURahXLWtSCGXCrJz+4BkxbAPT7A=,iv:mjA+GCM+Cd+b6SzvYJZ8xfd/ermUHZ4m5+FXN7DWnK0=,tag:lNjwB2H12NbQ8v4L7EGkDg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
