apiVersion: v1
kind: Secret
metadata:
  name: valkey-secret
  namespace: valkey
stringData:
  valkey.conf: ENC[AES256_GCM,data:PGMNxz42cJvQkMIhT/3QaY0F+jr1qRpA2iaO1CunPzjM+q9ji9PlzrwAN8xzQSULuibXkDK/9B0SYXNQTLTWwpwKx8e0poKq5tXDPc8UKUlS36fK5KXbH4BmRynP8XWQHuy8W6cGjCWZTb4+7iSWTgWVKkZrT1/cjrfxxBsyGRBkHlxjRvjtXPwyiYukKv8CkhTlZNk2OecVZ46z2H9yd8tmgCavFzqklnOWJqAD2BzRa7zx9dw10/Rbl/gQtl1BDIvSyATGHszcgK/CnI4CnU4JyXZDE3DA7+i6lWYf5CsgPN77lgBLT8iXOvTTdaYmpPirGLY10ZfKkVWOnCeqlXQusoOYceX2pae8idtR0J+pdTkhcvxDRWtCzHGJHJ8WFD8ru5DQg92Vt85Fuvl2J9JaMQf+wKzFH0l8O58NhtsyQTgFNvQIAVLSzRt7t37xwLNeBPAHaohiNQ1AYxy9pu07L7uUNA7trJiMN9bgoXM7+NWvUsKLXg9JeipcPWzR/T2iEtIkwo8YuWsynGoOtCR/8i/MZhbFt9yYZdlIxFS5NgWROY60P0eQ1C6YFvrWxCk/hwF+KqT6jU7q0jMJ7j83is/TqXrP0hTEGHkfNl2dL8cQT+q+tSFKkrrIuJIeREhLyBy4hG1OVOdBY4saquyL5+2yTc5KqpPxgYIXSOT7U2QE0grDBwUa,iv:ELbGMPMrEx1K2gcgNYAs4RLtVYrYB5r1Mzzood96EW8=,tag:Toq3OpNsnJu8vn/9eUWotw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaUFpdjBHcU5ZRDg5T3JH
        VUo3UWI3ekdUMHJyNGgwQ1RIYkg3MS9HdUhNClpkZkg1QmZpdFZIaWE5TE5DR0F3
        ODlpWWcrMytjVjVCVmovekd5UFlqSzgKLS0tIHVNUFMvRVRmNVVRaVVzWGFrbzhh
        L2xmNHYzaVRiTk50dUlkc1VTR0JLYzgKtrFRvMFnZbJOvsE/6KxOBKD5pjPKnllH
        Rd1NjeOKSU0WZw7NsHkrMyPYRjHFekyiH7RmHRKYCRg9MJqjLI2Zqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T19:58:42Z"
  mac: ENC[AES256_GCM,data:+cmt4J9jyX0GCs3CRYPSCCz+ihlApzPnqe/INcJSwGY0wKPUcLBapn/n1gDHT7H3iZSi2HwhFf28Znt39AdOg4M5l3wN8Fnc/eedcIsM8hu+ZhDX8zOSyDSBlsVaF+t7dkCR/xdEVyuBQY+YegS57zhUkNzgDtpRm5dWtlRwNtA=,iv:8N2aVb/+uNgpE0e2lls9hCW8GQCyQgmarPNnjBKv/z4=,tag:XwnU9vo1872rkaxMrd64XQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
