defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile: { type: RuntimeDefault }

controllers:
  formbricks:
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18.6@sha256:b6d3af974df781c673d37e49bdddfa14a6f5be28b18d2cb7713f0449bea4057b
          pullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: formbricks-secret
    containers:
      app:
        image:
          repository: ghcr.io/formbricks/formbricks
          tag: 5.4.2@sha256:4c32097d49ae9b5c53ffb42716f1302e0e5a26e6ea43914333feb4c53211a139
        env:
          EMAIL_VERIFICATION_DISABLED: "1"
          DANGEROUSLY_ALLOW_WEBHOOK_INTERNAL_URLS: "1"
        envFrom: *envFrom
        resources:
          requests:
            cpu: 500m
            memory: 256M
          limits:
            cpu: 2000m
            memory: 2048M
service:
  app:
    controller: formbricks
    ports:
      http:
        port: 3000
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.heremag.free
    hosts:
      - host: forms.heremag.free
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - forms.heremag.free
        secretName: heremag-free-production-tls
