apiVersion: v1
kind: Secret
metadata:
  name: adguard-exporter
stringData:
  ADGUARD_SERVERS: ENC[AES256_GCM,data:0914uV0OPy4AoGOJNHDXYNa8pY4dRAnOCuJQpyoS8NYbyuUN8g==,iv:oTRxYo2TI8f5fqklOR7NbxkGezQOheOGm32Ue/yuMVY=,tag:rR1aSH8tAra4C23slda/hQ==,type:str]
  ADGUARD_USERNAMES: ENC[AES256_GCM,data:Runz0R3CFG7iFS6WCX/V,iv:et2LEgWji8U1xDvJUJ9CocjTZoUxyseEgdBLlcMMNvM=,tag:mZa7KCe1HuEw0mMSRv5uKg==,type:str]
  ADGUARD_PASSWORDS: ENC[AES256_GCM,data:h0bVoy1fa4rcxraOpApgmjd5asiRPn2RSwatBde4JfuGY6VdjTdngrsAs7xISaOijFII14KoqFX55JiQ1RJkIrgZDee7f6oLTRJNoEukx7avBALSVrfhONhxM9Z5eob/ZA==,iv:IPJtQ8EsKTlxUrX7jCimdYFVqwnawkVXWimBWul+eMc=,tag:zSwkFNJxTHzz0amO0IaQzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ2QxckVTcFhHWkhBdlBU
        UXBielBQVlVmdUFDczFXeW9XNUtRditEdGs0CjlTZVNnVjZadjM3SXI5cEM4ekdF
        UUVrdkpqV0JGYnVaeTRqRytVSnhOeGMKLS0tIHZNZDNrdGhrMi85RW5EY1lCQjc2
        TCs3c1l4Rit1enRDaWp4V05YQ2NNUzQK0wK56HBuieWYSUS7+wr8nPW9c3NNOMXI
        UO9WuPioLQ6cPmMGZWXGAlew2qi4VsaZTy7dMRvbO8i4nWmMDL/y6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T16:42:07Z"
  mac: ENC[AES256_GCM,data:5ATB3gH6rVt54BBkYnZzu3xMjNfj6bN1BWdLf+pnV2f9fhda2SxpHBzyLvCvX2Zdq+jRPXMhxpbHDsY6dVlE1P678JHnJH2yJ8ojosjuWxE76dCND84Q08Xu2WFQT47drz3f8lHub1xSoRtdhkRXbK+P0k2mcP88SzSm1h27ca0=,iv:e/SSD6B2aIeUcq/vNkfFwK7kJ/77Be5ihpp4m3eKtMA=,tag:hyDR/Yz/vGXyKc59KUKunA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
