apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lastglance
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/lastglance/lastglance
      targetRevision: main
      ref: lastglance-repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 5.0.1
      helm:
        releaseName: lastglance
        valueFiles:
          - $lastglance-repo/kubernetes/apps/lastglance/lastglance/values.yaml
  destination:
    name: in-cluster
    namespace: lastglance
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
