apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  config.yaml: |
    ---
    originRequest:
      originServerName: "external.laboratory.casa"

    ingress:
      # Everything goes to the Envoy Gateway `envoy-external`.
      - hostname: "laboratory.casa"
        service: &gateway-svc https://envoy-external.network.svc.cluster.local
      - hostname: "*.laboratory.casa"
        service: *gateway-svc
      - service: http_status:404
