apiVersion: v1
kind: Secret
metadata:
  name: adventurelog-secret
  namespace: adventurelog
stringData:
  #ENC[AES256_GCM,data:rtgra3u4eUiblI0BgByF5Bt61Q==,iv:IAu2oKnB/u9VH1K+TJO9FqAPvbIV9+mo4B0Dt41wdgI=,tag:i6yL01XKkvI20xi38yZ94w==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:62vpw8gqdYTSwmt9,iv:tw+8s4tuRMWK1LjBfMu7a6giIiHLeRrxp7jJd6DDK4c=,tag:S+zBJy7J4o5GkBz1YTS94Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/sO01J9x/fxpNzYBWBbIzKWLy50PiUggQU6RS5oUkoIhTlN2ODlQTt5BhrBrpAZF3w==,iv:pQIMI9Vv933G6BzqJkbbGDCG4qrhw2jjy322RAHd2jc=,tag:JOlBA7hSM4xNSdrtlqPRNw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:q/ZforLu2qUHRuAH,iv:7wyIu+rm4V0DxFg7ewrsi+RVA1+fMzblwTOY4PWAa3A=,tag:c8HK7aFVkj4Fl+Q6RdZIzQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OSc2O3hW1zS3SwyWEqb463Fwar0fixzAUw==,iv:sW+KvGuqk19a8Bskk5ZEMl5f8SnqHfNVvkPAAdEwPeU=,tag:ijoBBwXibfhYWtVsMkGmeQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:5LT2AyDdjOQIZzH1dHfpU6xL98B9mjK64q4=,iv:NYJtXbalUZpBd2NSG7CtC8YQbqDS7mm3g2gpgZzEG+A=,tag:yYdFQhEqeuoCP8J8Tuzvog==,type:str]
  #ENC[AES256_GCM,data:9uWL6sfuj5j2V5RNd2pmh39mbKCnLDwCjZbfvHP2Bdz1jrhkhn1zSSFsIC42QE85hA==,iv:9x7nDz29lmpXwMemVqY3AMlhzG6nvvWQXh4yvtjB1aA=,tag:syo2K8iy/kIUwZ/gCE9TWg==,type:comment]
  PGHOST: ENC[AES256_GCM,data:73HHOmEdQIvSHcJni1e1pyiiRhePp+HZVGQoYsV+zwlq27T3IxrcIT4SgUGxzVOuCw==,iv:ntmhw50S4Y0DIGdf+I/xWzwJejpKXw990sGNusv+f7k=,tag:I9TMOgahCis1qXREypG1Wg==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:Ki08T3J6yIl0iHjN,iv:3yCYjwneyOl0Y1TXZAnSAxhAl5EMMDRseMt+TmVtQ18=,tag:EX3bNnzEN4dXVhu5c6TC+w==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:OkFIjeNdO70Fyt+/,iv:COsYCRE6GdguUQJuUFh3Al9pNCSu34NtnlFKdKIVTlY=,tag:uo/rvqrkTJU6z/94rGvKIQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:SFSolZLasteydeW8ROaxo7dLgmmamV9ABQ==,iv:dyuMyHD/9sTon83s/lTRaQ13IOwBvOw2EAC0R23bzvw=,tag:vU6L5JLnCsDHOkkBnTr5NA==,type:str]
  #ENC[AES256_GCM,data:cVI7VCKslUeV7bnbZpSyRjH8,iv:KbCc/j88Lyi0Xnqdo/GiehW8fJhj05TThMyVAq8UVoA=,tag:sXqc3+ff/jT0HsZNnb+W5A==,type:comment]
  SECRET_KEY: ENC[AES256_GCM,data:GmOTmI+ERBVqYmVsIvj1JJet5bmrZrreNKRVL905IzPk0LEIQ+zlOyZHV5a7BuGDUtowzYIdfe4qlnS2IRd4mg==,iv:ghe/uK4ulIoTjSNmYBuHbDlyD+O335IGXWBaiOGrHfY=,tag:/oMFNOqUDfL1+lEmfLeBaQ==,type:str]
  #ENC[AES256_GCM,data:I5f6hVNxxbfx5m3aKwq/Vt5fLYNM,iv:nnAhIRBkXQwVkaUNE7goQOwZFCt/NyECYvbtVAilAoM=,tag:Q0eqpl2ZNdoGS3thpIFyqg==,type:comment]
  DJANGO_ADMIN_USERNAME: ENC[AES256_GCM,data:crHG,iv:V7PHcKrczXUZX5JS3KRAidypKeeXP5g3E6Qq0Vjzrdo=,tag:/PkJJAQx5FdvDHy4+eOI4w==,type:str]
  DJANGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:39RLaFLW3kwHJZKXzy190qOBMnT3vqinMA==,iv:RHTB7Q245rDzGDaKESDY8lcS0FDEcXh4nQLf7dAx1DU=,tag:ojAWQJRYSYrlIafFnqm84Q==,type:str]
  DJANGO_ADMIN_EMAIL: ENC[AES256_GCM,data:QPIxzN9uYuuABabtYh+QUAPk7Q==,iv:vKTiLX9RnPZ8yrPxvnX6Z/35+nHHOe391IJIE2U/mak=,tag:zump2IB0znCCzVpk0UhzvA==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLazVuQ2JlclNDNTExK010
        R0I4bjFZa2ZpMktmVEFqWFAwb25KNEhaM2hJCnBwZExpbXJRVzFkVFBDeTRrT2FP
        RVJ3UXY4cG5KbWR3TEkwOUVzc2tKaG8KLS0tIDRFRXdPMVdrWDlFalJZeEFUSEtU
        U2xxQS9kOFllWnJSN0RraHdvejZHRG8KoItJRDQZaSS4JpyBpx3R2jZIfKvPPdPD
        SwtKMS+qep1n0sFmuk7eQaHJHbLTPKCZHwEykFrmYoaV5frBuuMvWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T20:58:42Z"
  mac: ENC[AES256_GCM,data:C9y5aagGBQyV+L/0b2kSWFTCriwwe1YjVED9k51gJ+gi9g9TdgwQvfV+LgD5YGu53DensR3jZcMQ++HomBidF78EKRefl7kzfKvcbDVtoAq9FkrHIre9iuQez5LAUEzNB0+pktvkNPubxBSkQgbww74FN6G7bmO1M9+E3vr+P44=,iv:btJ9Cag+aveLWgvhYiUgZ4xDOXOWLwOLI05PuVNJzrs=,tag:H8n8uEXrrai1m5Edl+RIbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
