apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: adventurelog-initdb
    files:
      - adventurelog.sql=./initdb.sql
    options:
      disableNameSuffixHash: true
generators:
  - secret-generator.yaml
