apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: adventurelog-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./adventurelog-secret.sops.yaml
