apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-heremag-free-configmap
  namespace: network
data:
  config.yaml: ENC[AES256_GCM,data:1YsR5RBih+lUUZpaXi6Nl8FU/lj3oy2lej3IVQdAfBiyhQI6Ajza2MWH9MFS1DeE2FDcoQfB/uwPoEF0fPzq9nh3bxWvvTnE7xJ8Rvlx134qSq6hh33Ogr8ijZGpHACuUXDUR2RI8j8Gdx9FZAqr3c9OAqhfF4FvfJzv1TnZhg0h/tMxPuYLJPie++BeRTBhwUh/Lc2+wKLrrpL+1AgLVNgqZDzvEWi37FpSDXaw,iv:JVfleYr0mDLZVkxZq8FGDVM0ehR7/MqM9+kZCJtv1LM=,tag:Mpsn4F0pNpbL0Erhbu/7Rg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOXVvNVQ1N0Z1ZTQ3bzNa
        SGw1WmQ4RlBUZC9oeitoZ01tWTRCWTFha2g0ClpEYjlPRFpSS0RxVEY4NzFaWG4v
        TkFoYXVaVnk0SENaaDR2MTVSUG5nWmcKLS0tIGZtQU83UG5qOWl1ZVI2dlZPYUVj
        TlpRRm85VmZtdzBYLzYzcmVBdHlRM3cKWcRtH6P8HW6jUexgQ2oxkDfA5bDOifE7
        pAHVlHP8Puau2/lbwzkdXBAUmEO0d1QyXlMxZPmkwDxy0aKbCRxhhQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T15:37:25Z"
  mac: ENC[AES256_GCM,data:MPCLbXu0Q5Fyop28AAhWb2SM+5WINGLaYUaCMQXSMbVfzUw2GJPKUjC3QaleBx1GtcQP2hpHODHUwleXXwfSYIkc+labYSwjYTRACB5ZmOIj6XlAicNiMZdTCPWI6ROTbGxPLiPSZ0sLiBh0d6/2KhYyUajN5vGuOBIHW+XiGLk=,iv:Ak3XC2h9l9Va0mgcurIz14wJ0XeO5XG28hDO7dmjRX4=,tag:2+zAfAsMEFRIYMZfIQ+4ww==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
