apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
  namespace: garage
stringData:
  AUTH_USER_PASS: ENC[AES256_GCM,data:S9mgMXZZlk2aNXlg3BYyKU/ycRRkh0Pfgc7p4MRIy/lHrY5bIFhJqR9zserhFJMesvfm3N0SfAzc6ffYOj6og1/QQLQ=,iv:WTJ/RJoeXfQdS93VQPja5olmv0BK5ncRgtm6B8hF/4Q=,tag:tldYhqtPoJoNFfscORGOsw==,type:str]
  metrics-token: ENC[AES256_GCM,data:UWvSBYOzhHPcaQ/EIkcTOn65P4FhpOEUkohQ/ULZX7P2AF3gCnsKUguvPnBwQJxQAbzXms/zlgJ0vTNyvFeF6A==,iv:reYBeQKNZl+i+zFCMnMes5pOwiyKIr/Y4K49UT9Lz2w=,tag:uDPE2DZQV7R9cTKfzKof+g==,type:str]
  garage.toml: ENC[AES256_GCM,data:A1WFheIJ/XqfkVb/SWKcHgs7TLU54FOukTBLDGk9s4SC2jpnta+pUY8//qdZXFrBZdHiQaKS3xW3sRWkrR2IqAOyoQTcjQi79MXWXgZ6FKux7U0yKOtqsQpJxTMu7lLtdHaobk6Pv++z2Q+J2Xdytq/d9WO0+dSOQE/MHtbUM83gkOpaHgV+CVtRHP2h4Ii2rlCe9XFa/tj8l4Hr3PB3XPt0UNcdAYcj+6Pzvb9vUq1zR73rbfMs+sH6xBzPyLqthLBtwGWKtP8dWhe7x8jbZqPV1K0NjWdCFtBrDkWikSTcGknnGLG9JVgOwNPlICw17rqv+MHfCp0ZmxDAw6tAIEQCRfnnYDKMNdNCHldD7m9aGlbHfMkK0ZA4yB9D6BrG57dVjIDOQBy05S/lFcgiLdD8mRavtahOu0M53Q9FjaJodxRe4+BgkzHMHipMynbaxUw2yJAlwFHiFv+V/CbGqlcJzXjI3F292nmJxptw1PXF53q8Ie1BGBPItAU/or1WJjV2Xdeknkl8SrDh/V1n2aoB0fCj8Hg+CJYDBvx5l0aihRxKAODNgyyq3+akm5xCf6SJJoX54EhuCTzDdSa4vQ/eHwcTOUifGLfMplvYHqME4lGHFq23o/b9XeRuBNx8yedLxb3uJ+gV4OhiNkpcJNnS5axh2H1JBVt+yUDn2SzpDEqGWOo/lT2DQHrkfBhHLCcVXB+HZJhnyOsRJfpFnOr3AoXUBv1PsRSedpaGNH4MElT+qbLlPwTwQZW8eqzC9b+g6E0CLBNO/nYrnS7OnSJNAP2kzcOsDpZZ3w6Qb+R51S5y0IWd7ljSDoB+92Yj6pT+ejXqrUliqV77dw2XtcYY7g0R+wEdHwGck+yLIy20cUBafaMiXzH0t7pfU8SdU/XUC0tOZT26EZU6j4cV0xmLdv+stqzgfCEUOK3XBek/tohug7b3hMk1is5gg2IhBaEoEz9R9sgErQ7yC3PNOUHvE/3tqPK3owJSgsH299Fovcw7ECXqoMFQ8QgZAtArFd1WOCyjX1DPCA6daHfd04xarE26U09LKqAx43Miw70dF+1/qzxTSTodycujh0N4LFxUg7osYOTSrzQ6W/UHfnb0hjqAMIQO4BewJDZKE8GVJOPunCwy2DRR5yY9kGADJh+lN/p9L/dLHbUdrjMqMh3XOy9u4ojiyEBjbSpNBeniR1wZPdX1ypY92K4x0oUUNq2vUL1413GiQY+ECUqUG0NKhhDF5TzZ,iv:G9Rm2FuXve8D/J25fcLRJazCLS2xmKoAsRQBJH0qqeY=,tag:lrge00kUttCBlzCrD9k8iQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaVJVU200MXgxQmJ5VDRK
        YTF6Ri83ZmZWYlNkTlZHaG9YUjZZZE4xSWdjCmVyVWljb1pVeVpaeDIyV2VTbGF4
        T1dZWXkwSTZXRFdhWGxNbnRwNTFjOE0KLS0tIDAzZTdMRExGUGdudHhIZ2o0ejF5
        d2w2RWgrSVNSV05zOGVka2h2S2hXSDQKpYolYfFPvZV8C28Od+0Y1hZ1Gpp2d+44
        V63rcXmHW/tlgu+ECTyQaG4qwh/vteo9KYPG54slMpZcZSrcXrIN8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-14T13:08:29Z"
  mac: ENC[AES256_GCM,data:WWewqQVpzG2B5nHdzinxILgAyJ7sqpal5emvmNgELHDFSo/+1Mg7GxIkmJhuSbF4fL6B5zeI6dzlQ3TjjzkI2uBUhkMsU5d5BBpzgYAB1ze0vw25h4iFAWWvrJq2PWwTBPcfnR0oQAeGWPCrbSsAjslwOs5AupFAW0eO+IMjN30=,iv:k76KjR7YGrDi1JBKH1mPwzN7fJCOWKfe3zL/fPswS94=,tag:Sq4XtwCxgp/3ETyOJOW5tg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
